### ISSUE TITLE
Create a first draft of a Technical Specification Document

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#1]
_As a **DEVELOPER**, I need to produce a technical specification document so that I can communicate with other people how technically I intend to implement Producer._

I need to produce a technical spec doc that shows how technically I intend to resolve the issues/requirements covered in the software design specification document.
This should detail a high level architecture, decisions on certain tools and technologies and identify communication between components.

**DoD:**
- [ ] A document, circulated for review by relevant stakeholders that details technically the proposed solution for Producer.

**Tasks:**
- [ ] Produce an initial high level architecture diagram.
- [ ] Add information to the document about the tools and languages that I propose to use.
- [ ] Add information to the document to provide a high level overview of the major components of the system.
- [ ] Add information to the document about how the components communicate with each other.

**Comment by NuclearRedeye** [comment]
https://docs.google.com/document/d/1mWR2WfvKKVIJZ7XIXhJ9ECiDhgePRQfWZrsu2QkNcO4/edit?usp=sharing
