### ISSUE TITLE
Create Initial Development Environment

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#114]
# User Stories

## Developer

_As a **Developer**, I need to create environment that allows me to code, test and deploy so that so that I can start to build the product._

# Description

Before I really get into prototyping too much, I need to put in place an environment that will allow me to concentrate on working. This needs to provide me with all the tools and documentation to setup a development environment from scratch, and allow me to make a code change that ends up published onto a staging environment that can be accessed by stakeholders. 
It needs to handle things like versioning, running tests and enforcing standards.

# DoD
- [x] Can commit a change, have the change run through a series of tests and then if the tests pass a new versioned deployment made to a staging/test environment accessible to users.

# Tasks

- [x] Investigate what CI/CD systems we have in place already at eLife.
- [x] Create an initial web server service.
- [x] Create an initial backend service.
- [x] Create an initial front end.
- [x] Create initial build scripts/system to build both modules and front end.
- [ ] ~~Repackage Texture to support new CI/CD system.~~
- [x] Create an initial set of unit tests that can be run automatically by the CD system.
- [x] Setup initial CD system and deploy initial version.

**Additional Tasks:**
_These might be needed depending on the above, they could just fall out in the wash however._

- [x] Setup an initial local development/testing environment.
- [x] Setup an initial testing/deployment environment.
- [ ] Create an initial coding standards document.
- [x] Setup a linter and create a configuration that enforces the coding standards.
