### ISSUE TITLE
Break the project into deliverable chunks so that we can estimate delivery milestones

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#12]
_As a **PRODUCT OWNER**, I need to organize my project into delivery phases and milestones so that I can estimate an expected delivery date for the business._

**DoD:**
- [ ] A project delivery schedule and GitHub backlog with milestones estimating delivery dates

Tasks:
- [x] Finalize and Agree on project MVP
- [x] Break the MVP into delivery phases
- [x] Detail work needed for each phase (MVP backlog)
- [ ] Estimate delivery of each phase
