### ISSUE TITLE
Display contents of 'Back Matter'

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#120]
# User Stories

## Author

- As an Author, I want to be able to view all the elements from the 'Back' section in the xml of an insights article so that I can check if the information is correct.
 
# Description

Libero Editor needs to have mechanisms for a user to view the information contained in the 'back' section of the XML document.

# DoD
- [x] Tested and Approved set of designs available in InVision for stakeholders to view.
- [x] All elements from 'back' section of a reference XML document displayed in Editor available for all to use on a testing/staging system.

# Tasks
- [x] Agree issues that need to be fixed based on usability tests.
- [x] Organise User Stories gathered by the team to ensure all stories are being addressed.
- [x] Create an initial design proposal for review.
- [x] Test initial design with required stakeholders.
- [x] Create design specification documentation.
- [x] Create a reference XML article(s) that contains all the potential tags/attributes that are required in the 'back' section to support an Insight Article.
- [x] Create a set of unit/functional tests for the back section.
- [x] Update Editor to support missing elements and attributes.
- [x] Update Editor so that supported elements and attributes work the way we want them to.
- [x] Test updated Editor against reference article(s).
- [x] Stakeholder review of updated Editor.

# Impact
- [ ] Research
- [x] Design
- [x] Develop
- [ ] Test

Risks:
- N/A
