### ISSUE TITLE
Login and Logout

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#121]
# User Stories

## Author

- As an Author, I want to be able to log in to and out of the Libero Editor so that I can access my articles.
 
# Description

Libero Editor needs to have mechanisms for a user to login and logout of the system so that only an authenticated user can access an article for viewing or editing.

# Consideration
- Would we want to prevent users selecting a name from the list but using an orcid profile that doesn't match the selection?

# Design
- [ InVision Design for Author Login Screen - Step 1](https://invis.io/A8WXRN9PQBF#/445518379_editor-Sign-In)
- [ InVision Design for Author Login Screen - Step 2](https://projects.invisionapp.com/d/main?origin=v7#/console/19776007/455219124/preview?scrollOffset=12762)
- [ InVision Design for Author Login Screen - Step 3](https://invis.io/A8WXRN9PQBF#/455219125_editor-Sign-In-3)

# Tasks
- [ ] Need to discuss with Exeter about how login works and if we they can include a token in the redirect link.
- [ ] Produce a login flow diagram and review and approve with everyone.
- [ ] Complete the remaining DoDs

# DoD
- [ ] As a user I should be able to click an obscure link to access an article in Libero Editor
- [ ] As a user, clicking the obscure link should create an active session for me to view the articles editor page.
- [ ] As a user I should be able to revisit the article using its 'editor URL' if I have an existing session
- [ ] As a user I should be prevented from visiting an article if trying to access via its 'editor URL' without an active session.
- [ ] As an Author I should be presented a 'splash screen' / layover which offers me the opportunity to identify myself from a list of Author names from the XML article
- [ ] As a staff member I should be able to select myself from the list of authors instead.
- [ ] As an author, selecting an author from the list who also has an ORCID ID in the article XML, I should be able to sign in with that ORCID account to gain 'verified' access to the article
- [ ] As an author, selecting an author from the list who does  **not** have an ORCID ID in the article XML, I should be able to register / sign in with an ORCID account to gain 'verified' access to the article.
- [ ] As an author signing in with ORCID as an author in the XML without an ORCID ID, an ORCID ID should be added to the article for that author and the client should show the ORCID logo next to it.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 5d
Dev: 10d

**Comment by NuclearRedeye** [comment]
Just some notes from the SIG meeting on 12th Jan 2021 where we asked for any specific requirements around authentication.

**Fabio:**
Will the tool be able to work without any form of authentication at all? In their workflow, they don't need any authentication or permissions system and hence don't want that to be a barrier for using the tool.

**Nate:**
On our side, the most common authentication is going to be cookie/csrf-based because the editor will be loaded on the same domain as the other parts of the system.
