### ISSUE TITLE
Retrieve an Article from Kriya

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#125]
# User Stories

## Production Staff

- As a member of the Production Team, I need to be able to open an article from Kryia in Libero Editor so that I can QC it.
 
# Description

Articles are currently stored in Kriya, and we need a mechanism to retrieve an article from Kriya and to store it either our backend or locally on a users computer. The current idea is that articles on Kryia are deposited into an S3 bucket as it transitions between states in the workflow. As such it should be possible to monitor these buckets for new object events, and to then act on those to 'ingest' an article into our backend.

# DoD

- [ ] Upon notification that Kriya has exported a new article, that article is automatically downloaded and stored locally on the file system.

# Tasks

- [ ] Create initial design document for the Kriya Data Format Adapter service.
- [ ] Get access credentials to the S3 bucket for Production data.
- [ ] Create an initial implementation of the Kriya Data Format Adapter service.
- [ ] Create an initial set of unit tests, targeting 100% code coverage.
- [ ] Create an initial set of functional tests.

# Risks

- We still don't have 100% clarity on the solution, with at the time of writing there still being 2 options on the table. First being a deep integration with Kriya, or the second simply being a customer of Kriya. Our preference, and the least risk option is the later which is what the work breakdown in this Epic currently assumes.
- Have had issues with Exeter putting content into the eLife S3 bucket in a timely and consistent fashion.

# Questions

- Need to understand how AWS credentials, if we role with the S3 bucket solution, can be safely stored and applied to a container.

# Impact
- [x] Research
- [ ] Design
- [x] Develop
- [x] Test
