### ISSUE TITLE
Convert Kriya XML to JATS

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#126]
# User Stories

## Production Team

- As a member of the Production team, I need to convert Kriya's XML to JATS so that I can use it in Libero Editor.
 
# Description

Kriya uses a different XML format than the format we want to use in our Editor, hence we will need to convert the XML to our desired JATS format.

# Tasks

- [x] Get a DTD for Kriya's XML format from Exeter.
- [ ] Updated technical design documentation.
- [ ] Update the Kriya Data Format Adapter service to convert the XML to the Editors internal JATS format.
- [ ] Create a set of initial functional tests to test both successful and erroneous input XML.

# Impacts

- [ ] Research
- [ ] Design
- [x] Develop
- [x] Test

# Risks
- We need Exeter to share information about their internal file formats.
- There might be issues converting the XML that make automatic conversion unfeasible.
