### ISSUE TITLE
Display article 'Metadata'

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#127]
# User Stories

## Author

- As an Author, I want to be able to view all metadata associated with my article so that I can check if the information is correct.

# Description

Libero Editor needs to have mechanisms for a user to view the metadata as part of the XML document.

# DoD
- [ ] Tested and Approved set of designs available in InVision for stakeholders to view.
- [ ] All metadata elements of a reference XML document displayed in Editor available for all to use on a testing/staging system.

# Tasks
- [ ] Agree issues that need to be fixed based on usability tests.
- [ ] Organise User Stories gathered by the team to ensure all stories are being addressed.
- [ ] Create an initial design proposal for review.
- [ ] Test initial design with required stakeholders.
- [ ] Create design specification documentation.
- [ ] Create a reference XML article(s) that contains all the potential tags/attributes that are classed as metadata required to support an Insight Article.
- [ ] Create a set of unit/functional tests for the metadata elements.
- [x] Update Editor to support missing elements and attributes.
- [x] Update Editor so that supported elements and attributes work the way we want them to.
- [x] Test updated Editor against reference article(s).
- [x] Stakeholder review of updated Editor.

# Impact
- [ ] Research
- [x] Design
- [x] Develop
- [ ] Test

Risks:
- N/A
