### ISSUE TITLE
Open Article in Libero Editor

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#128]
# User Stories

### Author

- As an Author, I want to be able to open a specific article in the Libero Editor so that I can view it or make changes.
 
# Description

Libero Editor needs to have mechanisms for a user to open an article in the editor. There should be some means from the Editors menu to select a specific article to open, at which point the editor should close any currently open documents and then fetch/open the desired article.

No need to support importing old content for now.

# DoD

- [ ] A member of the production team can open and view an article that is currently in the production phase in Libero Editor by changing the DOI number in the query args in the URL.
- [ ] A release, deployed onto the staging system that can be accessed by stakeholders for testing.
- [ ] Reviewed and approved by the relevant stakeholders.
- [ ] ~~A link on the Exeter Dashboard that when clicked will open a new tab with Libero Editor and open the specified article.~~

# Risks
- N/A

# Subtasks
- [x] Setup localstack for blob storage locally with two buckets (kryia and editor)
- [x] SQS service to listen to new files and copy over
- [x] Following SQS ingest task, place files in DB
- [x] An endpoint that takes an article id and fetch relevant xml from blob storage
- [x] An endpoint that takes an article id and edited content to persist to storage
- [x] An endpoint for article assets (maybe a signed url)

**Comment by norisalsaadie** [comment]
Potentially use https://github.com/localstack/localstack and https://hub.docker.com/r/localstack/localstack
