### ISSUE TITLE
Display article 'Figure' assets

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#129]
# User Stories

## Author

- As an Author, I want to be able to see 'Figure' assets as part of my insights article so that I can check that they are displayed as intended.
 
# Description

Libero Editor needs to have mechanisms for a user to view figures with correct placement as part of the XML document.

# DoD
- [ ] Tested and Approved set of designs available in InVision for stakeholders to view.
- [ ] All children of a 'fig' element from a reference XML document displayed in Editor available for all to use on a testing/staging system.

# Tasks
- [ ] ~~Agree issues that need to be fixed based on usability tests.~~
- [x] Organise User Stories gathered by the team to ensure all stories are being addressed.
- [x] Create an initial design proposal for review.
- [x] Test initial design with required stakeholders.
- [x] Create design specification documentation.
- [x] Update or create reference XML article(s) that contains all the potential tags/attributes that are supported in a 'fig' element to support an Insight Article.
- [ ] ~~Create a set of unit/functional tests for the 'fig' element.~~
- [ ] ~~Update Editor to support missing elements and attributes.~~
- [ ] ~~Update Editor so that supported elements and attributes work the way we want them to.~~
- [ ] ~~Test updated Editor against reference article(s).~~
- [x] Stakeholder review of updated Editor.

# Impact
- [ ] Research
- [x] Design
- [x] Develop
- [ ] Test

Risks:
- N/A
