### ISSUE TITLE
Editing 'Author Information'

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#130]
## Description
Libero Editor needs to have mechanisms for a user to be able to edit 'author information' as part of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for editing author information.

## Epic level user story
- [ ] As an Author, I want to be able to edit 'Author Information' associated with an Insight so that I can correct any errors.

## User Stories
- [x] As an author, I want to be able to edit the first name(s) + initials and surnames for authors so that I can correct any mistakes.
- [x] As an author, I want to be able to add a prefix/suffix to an author so that I can ensure they are distinguishable from a parent or child with the same name (e.g. Fred Smith Jnr).
- [x] As an author, I want to be able to remove a prefix/suffix from an author so that I can correct any mistakes.
- [x] As production staff, I want to be able to change the author order so that I can correct mistakes on behalf of the author.
- [x] As production staff, I want to be able to add a new author so that I can include any missing authors.
- [x] As production staff, I want to be able to remove an author so that I can update the authorship of the article if required.
- [x] As production staff, I want to be able to remove an ORCID ID from an author so that I can remove errors in ORCID attribution.
- [x] As production staff I need to be able to see whether an ORCID is authenticated so I can ensure the correct information is passed on to the downstream processes.
- [x] As production staff, I want to be able to remove corresponding author status from an author so that I can correct this information if requested.
- [x] As production staff, I want to be able to add corresponding author status to an author so that I can correct this information if requested.
- [x] As production staff, I want to be able to edit an email address associated with an author so that I can correct this information if requested.
- [x] As production staff, I want to be able to remove an email address to an author so that I can delete incorrect information.
- [x] As production staff, I want to be able to add an email address to an author so that I can add missing information.
- [x] As an author, I want to add a competing interest statement to an author so that I can acknowledge conflicts of interest.
- [x] As an author, I want to indicate that an author has no competing interests so that this information can be captured.
- [x] As an author, I want to be able to edit any competing interests statements so that I can correct any mistakes or update the details.
- [x] As an author, I want to be able to edit a bio so that I can correct any errors.
- [x] As an author, I want to be able to add a hyperlink to a bio so that I can link to an external site.
- [x] As an author, I want to be able to remove a hyperlink from a bio so that I can correct errors.
- [x] As an author, I want to be able to apply formatting to text in a bio so that I can add emphasis.
- [x] As an author, I want to be able to remove formatting to text in a bio so that I can correct errors.
- [x] As production staff, I want to be able to see where an ORCID associated with an author goes so that I can check that correct page is linked. (Is this part of validation?)

## Linked design(s)
- [Author info prototype](https://invis.io/3AVVJOBPKZT#/403947722_article-Author-Info-1)
- [Drag and drop author list ordering](https://invis.io/3AVVJOBPKZT#/403975769_article-Author-List-Drag)
- [Author competing interests](https://invis.io/3AVVJOBPKZT#/404000132_article-Competing-Interests)

## Linked requirements
- Author names #23
- Author IDs #24
- Corresponding author status #25
- Email address #34
- Author competing interests #31
- Bio #84

## Additional notes
- [Article on drag patterns for accessibility](https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09)
- [See cards design pattern rationale...](https://ui-patterns.com/patterns/cards)

## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
- N/A
