### ISSUE TITLE
Export an article in JATS XML

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#131]
# User Stories

## Production Team

- As a member of the Production Team, I need to be able to get a version of an article in eLife's JATS XML format.
 
# Description

Libero Editor needs to be able to export an article to eLife's JAT's XML format so that it can for example be sent to Exeter for a PDF be generated, or sent to Continuum to be added to the Journal.

# DoD
- [ ] As a user, I should be able to make a call to an API and get back an JATS XML version of the specified article.
- [ ] As a user, I should be able to specify which eLife xml version I want the response in, e.g. 1.0 or 2.0.
- [ ] Additional tags not displayed in Editor, e.g. the typesetting tags, should be preserved and written out.
- [ ] As a user, I can validate the XML output against the eLife Schematron and have it pass without errors or warnings.
- [ ] Solution deployed onto a staging environment.
- [ ] Solution reviewed and approved by stakeholders.
