### ISSUE TITLE
Save from Libero Editor

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#134]
## Description
Libero Editor needs to have mechanisms for a user to save an article.

## Epic level user story
- [ ] As an Author, I want to be able to save my article so that I don't loose any changes that I've made.

## Linked design(s)
- [Design for save notification](https://invis.io/A8WXRN9PQBF#/442344970_le-Medium-Device-Idea-1c)

# DoD
- [x] Can open an article, make a change, close the article, re-open the article and see the change preserved.
- [x] Saving transparently and automatically, at an as yet to be decided frequency.
- [x] When a save is happening, there should be some form of display for the user so that they know it is happening.
- [x] If the backend isn't available, then changes should be queued until the backend is available.
- [x] When saving has failed, there should be some notification or similar so that the user is aware that there are still pending changes.
- [x] Implementation deployed to the staging environment.
- [x] Solution reviewed and approved by stakeholders.
