### ISSUE TITLE
Editing 'Article Information'

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#135]
## Description
Libero Editor needs to have mechanisms for a user to be able to edit the article information of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for editing article information.

## Epic level user story
- [x] As a Production Editor, I want to be able to edit 'Article Information' associated with an Insight so that I can correct any errors.

## User Stories
- [x] As an author, I want to be able to edit the keywords so that I can correct mistakes.
- [x] As an author, I want to be able to add new keywords so that I can include missing information.
- [x] As an author, I want to be able to delete keywords associated with my manuscript so that I can make sure that my work is correctly.
- [x] As an author, I want to be able to edit an abstract so that I can correct any errors.
- [x] As an author I want to be able to add sub headings to an abstract so that I can structure the content.
- [x] As an author, I want to be able to add and remove styling to the text in an abstract so that I can correct any errors.
- [x] As an author, I want to be able to add and remove equations to an abstract so that I can correct any errors.

## Linked design(s)
- [Keywords prototype](https://invis.io/3AVVJOBPKZT#/404142464_keywords)

## Linked requirements
- Keywords #37
- Abstracts #38

## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
- N/A

**Comment by NickDuf** [comment]
@JGilbert-eLife we have a number of stories associated with this this epic around abstracts. Do you think the stories below fall under our Insights MVP?  

- As an author, I want to be able to indicate the language for an abstract so that I can add translated summaries to an article.
- As production staff, I want to be able to add one or more abstracts so that I can capture a summary of the article.
- As production staff, I want to be able to remove an abstract so that I can correct errors.
- As production staff, I want to be able to set the type of abstract so that I can indicate what kind of summary it is.
- As production staff, I want to be able to change the type of the abstract so that I can correct any errors.

**Comment by JGilbert-eLife** [comment]
@NickDuf These would, I think, all fall outside MVP. They're not really relevant to Insights.

**Comment by NickDuf** [comment]
@JGilbert-eLife I guessed as much. Thanks

**Comment by NuclearRedeye** [comment]
Need some clarification in the designs for how to support different abstract types, e.g. impact statements.
