### ISSUE TITLE
Adjusting 'Text Hierarchy'

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#136]
## Description
Libero Editor needs to have mechanisms for a user to be able to adjust the text hierarchy of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for creating text hierarchy.

## Epic level user story
- [x] As an Author, I want to be able to adjust the 'text hierarchy' of an Insight so that I can make sure that the information is presented as intended.

## User Stories
- [x] As an author, I want to be able to see the hierarchy of section headings within an article so that I can check this is correct.
- [x] As an author, I want to be able to add a new heading to my article text so that I can create a new section.
- [x] As an author, I want to be able to edit existing headings so that I can correct errors.
- [x] As an author, I want to be able to adjust a heading's level of hierarchy within my manuscript so that I can organize my content. (we need extra heading levels to meet SIG requirements)
- [x] As an author, I want to be able to delete a heading so that I can merge one section of text into another.

## Linked design(s)
- No design required to support this epic

## Linked requirements
- Sections #40

## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
- N/A
