### ISSUE TITLE
Version an Article

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#138]
# User Stories

## Production Team

- A a member of the Production Team, I need to be able to version a document so that I others can see when an article has passed a certain milestone or part of the process.

# Description

Libero Editor needs to have a means to allow a staff member to version/tag an article, for example to mark v1.0.0 of an article that has passed QC.

Tasks:
- [x] Research
- [x] Design
- [x] Develop
- [x] Test

Risks:
- Not sure how this might impact Kriya or Exeter.

# Design
- [InVision Design File]() 

# DoD
- [ ] When logged in as a user with appropriate permissions, can use some element on the UI to move the article to the next phase of the production process.
- [ ] When an article moves between stages, a payload needs to be sent to Exeter to update the status on the Kriya Dashboard.
- [ ] Solution deployed to a staging environment.
- [ ] Solution reviewed and approved by stakeholders.
