### ISSUE TITLE
Adjust 'Style Formatting' for text

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#139]
## Description
Libero Editor needs to have mechanisms for a user to be able to apply and adjust style formatting to the text displayed as part of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for applying formatting.

## Epic level user story
- [x] As an Author, I want to be able to adjust the 'Style Formatting' applied to my text so that I can add emphasis.

## User Stories
- [x] As an author, I want to be able to apply style formatting to my text so that I can add emphasis. (Do we need named-content (for gene sequences) for MVP?)
- [x] As an author, I want to be able to remove style formatting to my text so that I can correct errors.

## Linked design(s)
- No design files needed to support this epic

## Linked requirements
- Style elements #41

## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
- N/A
