### ISSUE TITLE
Define what software configuration means to the Production team

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#14]
_As a **DESIGNER**, I need to understand what requirements the Production Team has for workflow configuration so that I can discuss how these could be accommodated in Libero with project stakeholders._

**DoD:**
- [ ] A documented set of examples demonstrating workflow configuration for the Production Team to share with project stakeholders.

Tasks:
- [ ] Plan a workshop to uncover workflow configuration requirements for the Production Team
- [ ] Run workshop focused on creating configuration examples with the Production Team
- [ ] Create an agreed document to share the outcomes of the workshop with project stakeholders
