### ISSUE TITLE
Request and Display a PDF of an Article

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#141]
# User Stories

## Production Team

- As a member of the Production Team, I need to be able to request a PDF be made of an article so that I can view it.
 
# Description

Libero Editor needs to have mechanisms for a user to make a request to for a Typeset PDF of an article, perhaps from the menu or some other method.

# Design

- [Design](https://invis.io/A8WXRN9PQBF#/450094650_pdf-Status)
- [MUI Patterns](https://material-ui.com/components/snackbars/#snackbar)

# Tasks
- [ ] Need to figure out how the XML and supporting materials will be supplied to Exeter so that the PDF can be generated.
- [ ] Need Exeter to ensure that they include the proofing instructions in the initial pre-edited bundles dropped into the production-processes S3 bucket.
- [ ] Need to ensure that those proofing instructions are preserved in the output from editor, although there presently is no requirement to display them in the frontend. 

Risks:
- PDF generation is done by Exeter, and as such we need to either work with the system that they have or get them to do some work to expose an API that we can use to request a PDF or similar. This might cost, or take time, or might be resisted by Exeter.

# DoD
- [ ] As a user, can use the PDF button on the toolbar request a PDF of the current article with my current changes.
- [ ] Whilst waiting for the PDF, a ribbon is displayed on the UI to let me know that the request is processing.
- [ ] Whilst waiting for a PDF, the button on the toolbar is disabled until the current operation has either completed, failed or been cancelled.
- [ ] A user can, if they desire, click a cancel button on the ribbon to cancel the in progress request.
- [ ] If generation of the PDF fails, then the ribbon should update to let them know that the operation failed, and allow the user to try again.
- [ ] Once the PDF has been generated, then the ribbon should update to let the user know that the PDF is ready and display a 'view now' button that when clicked opens a new browser tab and displays the PDF using the web browsers built in PDF viewer.
- [ ] If the user refreshes the page whilst a request is in progress, then when the page reloads the ribbon should re-display to let them know that the PDF is still being generated. (Or if it has finished, display the relevant ribbon).
- [ ] When a PDF is generated, the latest version should be stored in the backend so that when it is sent downstream to continuum the PDF is available to bundle.
- [ ] Solution deployed to a staging environment.
- [ ] Solution reviewed and approved by stakeholders.

**Comment by Cooryd** [comment]
No longer project requirement
