### ISSUE TITLE
Adding and editing 'Citations'

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#143]
## Description
Libero Editor needs to have mechanisms for a user to be able to cite assets and references that are part of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for citing references.

## Epic level user story
- [x] As an Author, I want to be able to 'cite' information presented in an Insight so that I can indicate relevance.

## User Stories
- [x] As an Author, I want to be able to cite a reference in the text of my article so that I can indicate the relevance of a reference from my references list.
- [x] As an author, I want to be able to delete a reference citation so that I can correct mistakes.
- [x] As an author, when using name/year citation, I want to be able to add both standard citations (“We are doing an experiment based on previous work (Smith et al., 2009)”) and conversational citations (“We are doing an experiment based on the work of Smith et al. (2009)”) so that I can use the style most appropriate to my text.
- [x] As an author, I want to be able to add a citation to a figure, table or another asset so that I can reference a relevant item.
- [x] As an author, I want to be able to remove an asset citation so that I can correct mistakes.
- [x] As an author, I want to be able to edit an existing citation so that I can correct errors.

## Linked design(s)
- [Reference citation prototype](https://invis.io/3AVVJOBPKZT#/404153309_reference-Citation)

## Linked requirements
- Reference citations #46
- Asset citations #45
 
## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
- N/A
