### ISSUE TITLE
Add a new Supporting Material

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#146]
# User Stories

[here](https://github.com/libero/editor/issues/49).
 
# Description

Libero Editor needs to have mechanisms for a user to add a new figure to the article.

# DoD
- [x] Can add a new figure to an article, and that file is uploaded and stored in the backend.
- [x] When opening an article, figures are loaded from the backend and displayed in the Editor.
- [x] Images uploaded in the TIFF format need to be preserved, but also converted to a format that can be displayed in Editor e.g. JPG.
- [x] When uploading an image the browser can't support, e.g. TIFF, then a placeholder image should be displayed until the backend has created a version of the image that can be displayed.
- [x] Solution deployed to a staging environment. 
- [x] Solution reviewed and approved by stakeholders.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 1d
Dev: 2d
