### ISSUE TITLE
Update a Supporting Material

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#148]
# User Stories

## Author

- As an Author, I want to be able to update a supporting material so that I can fix errors or defects in the article.

# Description

Libero Editor needs to have mechanisms for a user to update an existing figure, for example to add a higher resolution version or make a small correction.

# DoD
- [x] Can upload a newer version of a figure, and see that displayed in the Editor.
- [x] Solution deployed to a staging environment.
- [x] Solution reviewed and approved by stakeholders.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0d
Development: 2d
