### ISSUE TITLE
Editing 'References'

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#153]
## Description
Libero Editor needs to have mechanisms for a user to be able to edit references as part of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for editing references.

## Epic level user story
- [x] As an author, I want to be able to edit a reference so that I can ensure that the information captured is correct and up to date.

## User Stories
- [x] As an author, I want to be able to add new reference to the article so that I can add missing bibliographic information.
- [x] As an author, I want to be able to delete a reference, so that I can remove any erroneous or unnecessary references from the list.
- [x] As an author, I want to be able to change a reference type so that I can adjust any incorrectly captured references.
- [x] As an author, I want to be able to edit a reference so that I can ensure that the information captured is correct and up to date.
- [x] As an author, I want to be able to auto-complete a reference from a database (e.g. crossref, via API), so that I can make sure that the information is entered accurately.

## Linked design(s)
- [Reference editing prototype](https://invis.io/3AVVJOBPKZT#/404176680_references)

## Linked requirements
- References #77
 
## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

Risks:
- N/A
