### ISSUE TITLE
Editing the 'Acknowledgements' section

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#154]
## Description
Libero Editor needs to have mechanisms for a user to be able to edit acknowledgements as part of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for editing acknowledgements.

## Epic level user story
- [x] As an author, I want to be able to edit an acknowledgements section for my manuscript so that I can correct errors and add any missing information.

## User Stories
- [x] As an author, I want to be able to add an acknowledgements section so that I can include acknowledgements to my manuscript.
- [x] As an author, I want to be able to edit an acknowledgements section for my manuscript so that I can correct errors and add any missing information.
- [x] As an author, I want to be able to add hyperlinks to an acknowledgements section so that I can link out to external resources.
- [x] As an author, I want to be able to add reference or asset citations to my acknowledgements so that I can cite other articles and assets in this context.
- [x] As an author, I want to be able to remove an acknowledgements section so that I can delete redundant information.

## Linked design(s)
- No design required

## Linked requirements
- Acknowledgements #65
 
## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
- N/A

**Comment by NickDuf** [comment]
Based on a discussion with James we felt that for eLife's use case having a permanent acknowledgement section that can neither be added or removed would suffice for MVP.

- In eLife's case the title is always Acknowledgements
- A blank acknowledgements input = no acknowledgement
