### ISSUE TITLE
Connect to Research Article

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#158]
## Description
Libero Editor needs to have mechanisms for a user to add information to an insights article about the research article that it refers to.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for linking articles.

## Epic level user story
- [x] As a member of the Production Team, I need to be able to put information into an Insights Article that links it to the Research Article that it is about so that there is a relationship between the articles.

## User Stories
- [x] As production staff, I want to be able to link two articles so that I can indicate they should be read together.
- [x] As production staff, I want to be able to remove a related article link so that I can respond to changes in publication plans or correct errors.
- [x] As production staff, I want to be able to change the type of link so that I can correct any errors.

## Linked design(s)
- [Connect article prototype](https://invis.io/3AVVJOBPKZT#/404185921_related-Article)

## Linked requirements
- Related articles #20
 
## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
- N/A
