### ISSUE TITLE
Edit an Affiliation 

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#174]
## Description
Libero Editor needs to have mechanisms for a user to be able to Author affiliations as part of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for editing affiliations.

## Epic level user story
- [x] As an author, I want to be able edit my affiliations so that I can make sure that the details presented are correct.

## User Stories
- [x]  As an author, I want to be able to add or remove affiliations from an author so that I can correct any errors in affiliation attribution.
- [x] As an author, I want to be able to add or remove authors from an affiliation so that I can correct any errors in affiliation attribution.
- [x] As an author, I want to be able to edit an affiliation so that I can correct any errors.
- [x] As an author, I want to be able to create a new affiliation and associate it with existing authors so that I can correct affiliation information.
- [x] As an author I want to be able to delete affiliations so that I can remove any added in error.
- [x] As production staff, I want to be able to clearly see the divisions between different parts of an affiliation so that I can check it has been structured correctly.

## Linked design(s)
- [Affiliation management prototype](https://invis.io/3AVVJOBPKZT#/404203563_affiliation-From-Author)

## Linked requirements
- Author affiliations #28

## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
N/A
