### ISSUE TITLE
Edit a Hyperlink

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#175]
## Description
Libero Editor needs to have mechanisms for a user to be able to edit hyperlinks as part of the XML document.

## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for editing hyperlinks.

## Epic level user story
- [x] As an author, I want to be able edit or add a hyperlink so that I can connect relevant information together.

## User Stories
- [x] As an author, I want to be able to make text into a hyperlink so that I can link out to an external URL.
- [x] As an author, I want to be able to follow a hyperlink out to the target so that I can check the link is going to the right place.
- [x] As an author, I want to be able to remove a hyperlink from the text in the article so that I can make any necessary adjustments before publishing.
- [x] As an author, I want to be able to edit the target for a hyperlink so that I can correct any errors.

## Linked design(s)
- No design required

## Linked requirements
- Hyperlinks #82
 
## Tasks
- [ ] Research
- [x] Design
- [x] Develop
- [x] Test

## Risks
- N/A
