### ISSUE TITLE
Design back matter section

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#189]
## Description
As an Author I want to be able to view the contents of the back matter section so that I can make sure that the information is presented correctly.

## Tasks
- [x] Gather, agree and link relevant user stories
- [x] Create initial design proposal
- [x] Hold design review with relevant stakeholders
- [x] Usability test design (if needed)
- [x] Design approved by relevant stakeholders
- [x] Break designs down into development backlog items

## User stories
- As an Author, I want to be able to see an acknowledgements section for my article so that I can check that this information is correct
- As an Author, I want to be able to see the reference list(s) for my article so that I can check it ahead of publication
- As a Production Editor, I want to be able to check references by type so that I can make sure that the information supplied is correct.

## Linked usability issues
- Adjust interface editing control placement (TS09) #195

## Questions to be addressed
- Does this presentation present any problems for users performing manual content checks?
  - Reference errors are typically picked up with system validation. Smaller errors would be identified and fixed in the same way as typos. Presentation was considered sufficient for this purpose.  
- Is the presentation of information meaningful and understood by all user groups?
  - Yes. Presentation was considered typical by all test participants
- Can users easily locate the mechanisms available to them for making content adjustments if errors are found?
  - Yes. Edit and delete affordances were easily discovered, understood and used. 
- Does this presentation approach effectively represent the final HTML output of the Article?
  - We believe so. However presentation should be consistent across editing tools, journal website and pdf output.
- Could presenting the information in this way cause any problems for external parties?
  - At present Erudit do not consider this to be a problem.

## Linked requirements
- Acknowledgements #65
- Reference list #76
- References #77
- Journal reference #78
- Book reference #98
- Chapter reference #99
- Conference reference #100
- Data reference #101
- Periodical reference #102
- Preprint reference #103
- Report reference #104
- Patent reference #105
- Software reference #106
- Website reference #107
- Thesis reference #108

## DoD
- [ ] An approved design solution translated into backlog items for development
