### ISSUE TITLE
Gather design requirement for article back matter

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#190]
# Description
Gather information needed to create and evaluate designs for insight article back matter section.

# Tasks
- [ ] Gather and add user stories to work ticket
- [ ] Add usability issues to be addressed to work ticket

# Dod
- [ ] Back matter requirement information added to work ticket
