### ISSUE TITLE
Create designs for back matter section

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#191]
# Description
Create and review designs for Insight back matter section. 

# Tasks
- [ ] Create first drafts of design
- [ ] Review designs with team
- [ ] Test designs if required

# Dod
- [ ] Approved/tested designs ready for development

# User stories
- To come

# Usability issues 
- To come
