### ISSUE TITLE
Fix math input control (TS06)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#193]
## Issue
Users are misunderstanding the math and equation input feature because their cursor is not automatically placed inside the form input as they start to type.

## Proposed solution
- [ ] When activating the math or equation insert control the user's cursor should automatically be placed within the math input text field.

## Tasks
- [ ] Live Libero Editor project updated based on above suggestion
- [ ] Share adjustment with team/consortium for feedback

## DoD
- [ ] Team/consortium approves adjustment
