### ISSUE TITLE
Adjust reference ordering for contextual pop-up control (TS07)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#194]
## Issue(s)
- Pop-up for inserting references is expected to be ordered by name et al. Authors typically look for references by first author
- List reordering based on selection is considered confusing and undesirable. Especially with longer list types.
- Insert menu option labelling is considered to be unclear by Authors. Work with production 

## Proposed solution(s)
- [ ] Adjust reference list insert pop-up to be ordered by Author et al
- [ ] Indicate selected list items without reordering the list
- [ ] We need to explore ideas for clearer labelling. Look for standard menu organisation patterns. Citation by type has been suggested. e.g. ‘Figure citation’ 

## Tasks
- [x] Create initial design proposal based on usability test report suggestion
- [x] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS07 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)
- eLife user stories require alphabetical author name ordering 

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
