### ISSUE TITLE
Adjust interface editing control placement (TS09)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#195]
## Issue
A significant amount of users do not make the connection between Texture's toolbar edit control and asset card editing. This connection is typically discovered through trial and error.

## Proposed solution(s)
- [ ] Place editing and delete controls in an easy to discover place on asset cards.

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS09 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
