### ISSUE TITLE
Remove page range input (TS10)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#196]
## Issue
Users found first page, last page and page range inputs confusing. eLife require first page and last page range inputs to be populated to receive page range XML for publication.  

## Proposed solution(s)
- [ ] Remove page range input option.

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Tasks
- [ ] Live Libero Editor project updated based on above suggestion
- [ ] Share adjustment with team/consortium for feedback

## DoD
- [ ] Team/consortium approves adjustment
