### ISSUE TITLE
Adjust management of citable assets (TS12)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#197]
## Issue(s)
- Contextual input menus found in Texture's toolbar lead users to believe that options do not exist.
- Deletion of citable assets leaves orphaned references in the article main text.

## Proposed solution(s)
- [ ] Make Texture's toolbar menu options display consistently, but disable options that are not available.
- [ ] Warn users of the consequence of removing cited assets.

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS12 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
