### ISSUE TITLE
Improve management of author information (TS13)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#198]
## Issue(s)
- A significant amount of users had difficulty determining corresponding author status
- A significant amount of users had difficulty locating author type information 

## Proposed solution(s)
- [ ] Use a broadly recognised symbol on author lists to indicate corresponding Author status (asterisk was frequently referenced during tests)
- [ ] Move the Article/Author information section out of meta-data modal window and into an expected place on the article (article bottom). Link both sections in the article TOC outline.

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS13 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
