### ISSUE TITLE
Improve mechanism for ordering article assets (TS14)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#199]
## Issue(s)
Most users did not discover the reordering option to manage author lists from the edit menu.

## Proposed solution(s)
- [ ] Create a drag and drop feature for all sortable assets. In-card numbering was also frequently mentioned which may provide a mobile friendly and efficient option for long author lists.

## Tasks
- [ ] Create interactive prototype based on current control 
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS14 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)

## DoD
- [ ] Resolved usability issue through a tested and approved prototype
