### ISSUE TITLE
Adjust prescribed asset first workflow for affiliation type information (TS15)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#200]
## Issue(s)
- Most users try to create affiliation details from their ‘Author card’ by clicking into the affiliation input. The prescribed asset first workflow is considered clunky and laborious.
- Affiliation address detail order is unexpected leading users to place information into the wrong inputs.
- A significant amount of users didn’t add the affiliation address details into the correct input fields.

## Proposed solution(s)
- [ ] Allow users to create article assets in place as well as their relative sections. A create new option accessible from text input menus to open a modal form section should help.
- [ ] Order affiliation details in a standardised way. Department type details first.
- [ ] Clearly display all expected affiliation input fields to users when creating new article assets.

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS15 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)
- This design pattern should be the same as used to resolve TS16

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
