### ISSUE TITLE
Adjust prescribed asset first workflow for funder type information (TS16)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#201]
## Issue(s)
- Most users try to create funder information from their ‘Author card’ by clicking into the funder input. The prescribed asset first workflow is considered clunky and laborious. Some users created the funder information card without assigning it.

## Proposed solution(s)
- [ ] Use a less prescriptive asset creation workflow which allows users to create assets in place and in their relative sections. A create new option accessible from text input menus should help.

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS16 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)
- This design pattern should be the same as used to resolve TS15

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
