### ISSUE TITLE
Adjust keyword input mechanism (TS17)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#202]
## Issue(s)
- Keyword input method is misunderstood. Users added all keywords into a single text field with comma separation

## Proposed solution(s)
- [ ] Use a standard keyword input design pattern

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS17 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
