### ISSUE TITLE
Adjust figure citation insert option (TS20)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#203]
## Issue(s)
- Most users were unable to discover the insert figure reference option because of Texture's contextual insert menu feature. In most cases users highlighted text and tried to add a figure reference link to it.

## Proposed solution(s)
- Texture's toolbar menu option should remain consistent with the option to add a figure reference to selected text.

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS20 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)
- It is possible this issue may be resolved by TS08

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
