### ISSUE TITLE
Adjust prescribed asset first workflow for reference type information(TS08)

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#204]
## Issue(s)
- The prescribed asset first workflow is unintuitive and considered clunky. A significant amount of Authors expected to be able to create references as they were about to cite them.
- Contextual insert menu causes confusion and frequently leads users to believe that some options do not exist.
- Lack of a save button when creating new assets causes users apprehension when closing the meta-data modal window.

## Proposed solution(s)
- [ ] Citing assets mechanism has a ‘new option’ in contextual menu
- [ ] Toolbar menu option should remain consistent, but disable options that are not available (see example)
- [ ] Modals used to create content should have clear save/cancel options

## Tasks
- [ ] Create initial design proposal based on usability test report suggestion
- [ ] Hold design review with relevant stakeholders
- [ ] Usability test design 
- [ ] Design approved by relevant stakeholders
- [ ] Break designs down into development backlog items

## Relevant information
- TS08 finding and recommendations, [Texture Usability Test Report](https://docs.google.com/document/d/1z58LAJVuKLjFRVuTDigXNQ_XZFaXTXiQOSRsEMKND48/edit?usp=sharing)

## Related tickets
- Adjust prescribed asset first workflow for affiliation type information(TS15) #15
- Adjust prescribed asset first workflow for funder type information(TS16) #16

## DoD
- [ ] Resolved usability issue through a tested and approved design solution that is in turn translated into backlog items for development
