### ISSUE TITLE
Design article body section

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#213]
## Description
As an Author I want to be able to view the contents of my articles body section so that I can make sure that the information is presented correctly.

## Tasks
- [x] Gather, agree and link relevant user stories
- [x] Create initial design proposal
- [x] Hold design review with relevant stakeholders
- [x] Usability test design (if needed)
- [x] Design approved by relevant stakeholders
- [x] Break designs down into development backlog items

## User stories
- [x] As an author, I want to be able to see the hierarchy of section headings within an article so that I can check this is correct
- [x] As an author, I want to be able to identify reference citations in the text so that I can check they are correct
- [x] As an author, I want to be able to identify asset citations in the text so that I can check they are correct
- [x] As an author, I want to be able to see if text is a hyperlink so that I can check this is correct
- [x] As an author, I want to be able to see ordered/numbered lists so that I can check they are correctly formatted
- [x] As an author, I want to be able see box content for my article so that I can check this is correct
- [x] As an author, I want to be able to clearly see my figures, so that I can be sure that none are missing and that their quality is sufficient
- [x] As an author, I want to be able to see any permissions information associated with an asset in my article so that I check this information is correct.

## Linked requirements
- Sections #40
- Reference citations #46
- Asset citations #45
- Hyperlinks #82
- Lists #81
- Boxes #54
- Figures #49
- Asset-level licensing #79

## Linked usability issues
- None for this epic

## Questions to be addressed
- Style elements #41: Is named-content (for gene sequences) needed for MVP? 
  - Not for MVP
- Special characters #80: We have unanswered questions in the considerations for these stories. Do we want to address special characters for MVP? 
  - We believe this is currently handled sufficiently in Texture
- Lists #81: This is an opportunity to address a number of Erudit's UI/UX issues. Are we willing to address these for MVP?
  - For MVP Textures management of lists is sufficient
- Boxes #54: How do we anticipate setting different box widths? Are Insight boxes different to other boxes in regard to XML? e.g. could they have a special tag? We only need to deliver key info boxes for MVP. They should support paragraph text with formatting only
  - We may only need the key info box for MVP that contains paragraph type information with formatting. key info boxes have a single column width applied.  

## DoD
- [x] An approved design solution translated into backlog items for development
