### ISSUE TITLE
Design article/author info section

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#221]
## Description
As an Author I want to be able to view the article and author information as part of my manuscript so that I can make sure that the information is present and correct.

## Tasks
- [x] Gather, agree and link relevant user stories
- [x] Create initial design proposal
- [x] Hold design review with relevant stakeholders
- [x] Usability test design (if needed)
- [x] Design approved by relevant stakeholders
- [x] Break designs down into development backlog items

## User stories
- [x] As a production staff, I want to be able to check the article type assigned in the XML header so that I can ensure the article type is correct
- [x] As a production staff, I want to be able to check the DTD version being used to create this document in Texture so that I can confirm it is the version my publisher is committed to using.
- [x] As production staff, I want to be able to see the journal details on an article so that I can check this information is correct.
- [x] As an author, I should be able to see the article ID so that I can use it for reference in conversation with production staff.
- [x] As production staff, I should be able to see the DOI so that I know what it will be upon publication.
- [x] As an author, I want to be able to see my article's pending citation details so that I can share them before publication.
- [x] As production staff, I want to be able to check the citation details for the article so that I can confirm they are correct before publication.
- [x] As an author, I want to be able to see the license information for an article so that I can confirm the correct license is being used.
- [x] As an author, I want to see the categories applied to my article so that I can confirm this is correct.
- [x] As an author, I want to be able to see which subject areas my manuscript has been associated with so that I check that this information is correct.
- [x] As an author, I want to be able to clearly see the title for my article so that I can check it is correct.
- [x] As an author, I want to be able to see which parts of an author name have been designated first name(s) + initials, and which surname(s) so that I can make sure this has been done correctly.
- [x] As an author, I want to be able to check the order the authors appear in the full author list so that I can make sure this information is correct.
- [x] As an author, I want to be able to see which, if any, ORCID ID has been associated with an author name so that I can check this information is correct.
- [x] As an author, I want to be able to see which authors have been designated as corresponding authors so that I can check this has been done correctly.
- [x] As an author, I want to be able to see an email address associated with an author so that I can make sure this information is correct in the published article.
- [x] As an author, I want to be able to clearly see which affiliations are associated with an author so that I can check this information is correct.
- [x] As an author, I want to be able to see which authors are associated with an affiliation so that I can check they have been correctly assigned.
- [x] As an author, I want to be able to see the competing interest statements listed for each author so that I can check this information is correct.
- [x] As an author, I want to be able to see the bio associated with an author or non-author contributor so that I can check the information is correct.
- [x] As an author, I want to be able to see any publication dates added to my article so that I can check they are correct.
- [x] As an author, I want to be able to see the history of publication events associated with my article so that I have this information for reference.
- [x] As an author, I want to be able to see if my article is linked to one or more additional articles.
- [x] As production staff, I want to be able to see the type of related article link so that I can check this is correct.
- [x] As an author, I want to be able to check the keywords so that I can make sure they are correct.
- [x] As an author, I want to be able to clearly see the abstract for my article so that I can check it is correct.

## Linked usability issues
- None for this epic

## Questions to be addressed
- How can we present author information at the top of the article as a modal and make affiliation details manageable?
- What would be looking for when we test this information?
- How does the consortium feel about taking the article/author info out of the modal window?
- How do authors and staff think this information should be organised? 
- How do authors and staff check this information?
- Is there any common ground between us and the consortium members for article/author info presentation?

## Linked requirements
- [x] Author names #23
- [x] Author IDs #24
- [x] Corresponding author status #25
- [x] Email address #34
- [x] Author affiliations #28
- [x] Author competing interests #31
- [x] Bio #84
- [x] XML header/DTD version #15
- [x] Journal metadata #16
- [x] Article IDs #17
- [x] Article citation details #21
- [x] Licensing and Copyright #22
- [x] Article categories #35
- [x] Subject areas #36
- [x] Article title #18
- [x] Publication dates #47
- [x] Related articles #20
- [x] Keywords #37
- [x] Abstracts #38

## DoD
- [ ] An approved design solution translated into backlog items for development
