### ISSUE TITLE
Review and document design patterns

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#235]
## Description
Review and document design decision making and patterns for reference as the project progresses.

## Tasks
- [x] Review current design patterns
- [x] Document each pattern
- [x] Review design patterns as a team
- [x] Update documentation based on review
- [x] Update project based on documentation

##Dod
Share and agreed documentation of design patterns to date.
