### ISSUE TITLE
Gather feedback on article/author information designs

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#236]
## Description
Review current state of design for article/author information with internal and external stakeholders.

## Tasks
- [x] Review design work with consortium members (patterns/editing/display)
- [x] Review design work internally (features/production/reviewer)
- [x] Adjust design based on feedback 

## Dod
Reviewed and approved designs for presenting and managing author/article information.
