### ISSUE TITLE
Tidy up and review project overview document

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#238]
## Description
Overview document update and review to include 'key value propositions' and 'publish review curate' sections. 

## Tasks
- [x] Include 'key value proposition' section
- [x] Include 'PRC' section
- [x] Review and update sections
- [ ] Sign-off

## Dod
Overview document updated and agreed by team.
