### ISSUE TITLE
Establish Libero Editor Special Interests Group (SIG)

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#252]
# Tasks
- [x] Agree role and responsibilities.
- [x] Schedule meeting to finalise agenda for meeting (For either 27th or 31st Jan)
- [x] Create initial CCLAs and MOUs.
- [x] Create issue templates for GitHub.
- [x] Create an initial set of collaboration/contributing guidelines.
- [x] Have a think about how contributors can propose changes to the design, and the 'gates' that those changes need to go through to be approved.
- [x] Review project goals.
- [x] Schedule Kick off meeting.
        - Presentation of goals.
        - Presentation of DoD.
        - Presentation of progress on the editor so far.
        - Presentation on the what we have discovered so far, what choices we have made and why. Our initial thoughts on some aspects of the tool and where we want to go with it. (e.g. Config)
        - Presentation of project management tools.
- [x] Agree on methods and structure of communication.
        - Agree on how Discovery will be done.
- [x] Establish a regular demo.
- [ ] ~~Understand what we need to do about a news letter for the project.~~
- [x] Understand and document how we will manage conflict between parties.
- [x] Rename GitHub repositories.

## Website
- [x] Get consensus from the Product Team about Producer vs Editor.
- [x] Create an initial first draft of the content for the product landing page.

# DoD
- [x] A process for requesting changes or proposing new features created and in-place.
- [x] Updated section on the Libero Website
- [x] Regular meetings setup and running.
- [ ] ~~Discovery processes in place and working. (1 discovery completed)~~
- [x] Contribution from external party reviewed and merged into code base?
- [x] Established list of stakeholders, contributors, roles and responsibilities documented and published to consortium.

**Comment by NickDuf** [comment]
@joelsummerfield it may be worth discussing with consortium members what expectations they have for short term configuration?

**Comment by NuclearRedeye** [comment]
@hdrury1  Rough outline agenda for the kick off meeting on Monday 3rd Feb.

Agenda:
- What, Why and How
- Q&A

Suggestions from Nick
Why we are interested in the project
- Project goals 
- Use case

How we are working
- Usability test docs & testing
- Interviews, research (my work experience)

Where we are at
- inVision brief walk through
- MVP what we will deliver this year (open, edit, tracked changes)
- Future deliverables (Author queries, validation...)

Other stuff
- Trello ideas board
- Feature/design request templates

**Comment by NuclearRedeye** [comment]
@hdrury1 The reason that I assigned this to you was to get a couple more of the tasks ticked off. Think we just need to send out some calendar invites for a regular set of meetings (e.g. an invite to demo progress). And also we weren't sure about the Newsletter and what was planned around that. I guess that a progress summary message on slack might suffice for now?
