### ISSUE TITLE
Design figure asset display

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#253]
## Description
As an Author I want... so that I ...

## Tasks
- [ ] Gather, agree and link relevant user stories
- [ ] Review current figure implementation as a team
- [ ] Add additional requirements if needed
- [ ] Stakeholder approval

## User stories
- [ ] As an author, I want to be able to clearly see my figures, so that I can be sure that none are missing and that their quality is sufficient.

## Linked usability issues
- No issues

## Linked requirements
- Figures #49

## DoD
- [ ] An approved design solution translated into backlog items for development
