### ISSUE TITLE
User test current designs

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#254]
## Dod
- [x] Tested prototype with supporting feedback added to relevant Usability Issues tickets 

## Tasks
- [x] Recruit suitable participants
- [x] Book study sessions
- [x] Remotely run testing sessions
- [x] Update usability test tickets and documentation
