### ISSUE TITLE
Special interest group webpage

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#255]
## Dod
- [x] Initial draft of page content internally approved by Libero Editor Team

## Tasks
- [x] Develop initial page structure
- [x] Flesh out draft content
- [x] Draft 1 internally approved
