### ISSUE TITLE
Review figure asset display requirements

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#256]
## Dod
- [x] Identify any work that needs to be carried out to complete this epic

# Tasks
- [x] Review current figure asset control against user stories and [Article type breakdown](https://docs.google.com/spreadsheets/d/1tGpQtUGATI6vL8LJ1UmsP5Zbpx9NBewaaQPecNmq900/edit?usp=sharing) spread sheet
- [x] Create missing design spec if needed
- [x] Provide update on figure asset requirement to the Libero Editor team
