### ISSUE TITLE
Create draft proposal for submitting design feedback

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#257]
# DoD
- [x] Draft proposal for new feature requests
- [x] Draft proposal for suggesting design improvements

# Tasks
- [x] Set out and review ideas for both documents
- [x] Share ideas for feedback
- [x] Flesh out initial proposals
- [x] Gather internal approval for documents
