### ISSUE TITLE
Review design work needed for the editing theme

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#259]
## Description
Review Libero Editor project to identify remaining design work to be added to the editing theme. 

## Dod
- [x] Tickets for agreed editing design work are  added to the Libero Editor project backlog

## Tasks
- [x] Review current project to identify areas for design work
- [x] Agree work to be carried out by Libero Editor team
- [x] Add design tickets to the Libero Editor project backlog
