### ISSUE TITLE
Review emails forwarded from production team

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#260]
## Description
Review authors correspondence emails sent by the production team to identify problems faced by authors during the proofing process.

## Dod
- [x] Create an customer feedback document based on Production team emails

## Tasks
- [x] Create feedback document for capturing and identify overlapping issues
- [x] Review Production team emails and add pull out insights
- [x] Share document with Libero Editor team for feedback
