### ISSUE TITLE
Setup Author interviews to create personas

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#261]
## Description
Interview authors to gather information to create personas for the Libero Editor project.

## Dod
- [x] Organise interviews with Authors.

## Tasks
- [x] Create an email template to recruit interview participants
- [x] Review Kriya feedback spreadsheet and invite authors to 1-1 meetings
- [x] Set interview dates
