### ISSUE TITLE
Reference list: Editing

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#265]
## Dod
An updated version of the hosted Libero Editor project including the agreed design specification for editing references.

## Tasks
- For Joel to define

## User stories
- [ ] As an author, I want to be able to add new reference to the article so that I can add missing bibliographic information.
- [ ] As an author, I want to be able to delete a reference, so that I can remove any erroneous or unnecessary references from the list.
- [ ] As an author, I want to be able to change a reference type so that I can adjust any incorrectly captured references.
- [ ] As an author, I want to be able to edit a reference so that I can ensure that the information captured is correct and up to date.
- [ ] As an author, I want to be able to auto-complete a reference from a database (e.g. crossref, via API), so that I can make sure that the information is entered accurately.

## Linked designs
- Linked inVision file to come

## Linked requirements
- References #77
