### ISSUE TITLE
Create an interview script for staff based personas

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#266]
## Description
Develop a set of interview questions to help the Libero Editor team to develop 'organisation staff type personas' to guide our decision making throughout the course of the project.

## Tasks
- [x] Develop a set of agreed questions to use during interviews
- [x] Deliver an agreed interview script

## Dod
- [ ] An agreed interview script to be used during 'organisation staff' interviews
