### ISSUE TITLE
Review editing epic design work with eLife team

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#267]
## Description
Review current design work for the editing theme to make sure that our user stories are effectively met.

## Tasks
- [x] Set up and conduct design review
- [x] Adjust designs based on feedback
- [x] Update editing epics with new designs

## Dod
- [x] A set of eLife approved design epics that we can share with SIG members
