### ISSUE TITLE
Prepare illustrations for Libero Editor webpage

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#268]
## Description
Brief/choose illustrations to support our agreed Libero Editor page content.

## Tasks
- [x] Select illustrations from current set that we may be able to use
- [x] Prepare illustration for webpage
- [x] Develop ideas for remaining illustrations 
- [x] Brief illustrator and agree cost of work

## Dod
- [x] Scope of illustration work agreed and illustrator ready to start work
