### ISSUE TITLE
Add design guidance documents and ticket templates to Libero repositories

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#269]
## Description
Set up ticket templates and guidance documentation for SIG and contributors to be able learn about how to contribute to the Libero Editor project.

## Tasks
- [x] Agree locations where documentation is to be hosted
- [x] Place files/content in agreed locations
- [x] Add ticket templates to repository

## Dod
- [ ] Libero editor guides and templates are set up in their agreed locations for contributors to use.

**Comment by hdrury1** [comment]
Added contribution guide to editor-docs: https://github.com/libero/editor-docs
