### ISSUE TITLE
Review display theme and provide feedback

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#270]
## Description
Review display theme so that project meets design spec

## Dod
- [x] Backlog items ready for next sprint

## Tasks
- [x] Review project against design spec and user stories
- [x] Raise tickets for any issues to be addressed
