### ISSUE TITLE
Setup individual review meetings with Sig members

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#271]
## Description
Share current designs with SIG members for feedback and learn more about each organisations use case for Libero Editor.

## Dod
- [x] Setup meetings with each PKP, Erudit and SciELO

## Tasks
- [x] Email key SIG contacts to request meetings
- [x] Set meeting dates with each organisation
