### ISSUE TITLE
Gather SIG feedback on details panel in Libero Editor

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#273]
## Description
We need to gather input from SIG members on how Article/Author information is displayed and managed before we can confidently move forward with a broadly adoptable solution.

## Tasks
- [ ] Share current designs with SIG members
- [ ] Document necessary changes

## Dod
- [x] Gathered SIG feedback on best approach for displaying and managing article/author information
