### ISSUE TITLE
Create initial environment with file monitoring

### ISSUE THREAD

**Issue by ilya-zhuravel** [libero/editor#278]
As a developer, I need to enable a file watch for the Texture library as it is getting cumbersome to have to keep running the build/debug scripts each time I make a change.

# Tasks
- [ ] run test app for texture from the same project (separate webpack target)
- [ ] setup file watch for texture lib and texture demo app 

# DoD
- [ ] as a Developer to start the application I want to run `npm start` only
- [x] as a Developer I want the demo app to reload automatically when I change any file in `/src` directory
