### ISSUE TITLE
Updates to Libero Editor website

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#293]
## Description
Work with comm's team to prepare Libero Editor webpage for release.

## Dod
- [x] Marketing communications have guidance and assets needed to update Libero Editor webpage.

## Tasks
- [x] All content needed for web page is handed over to Marketing Communications team
- [x] Approved page designs with Marketing Communications team
