### ISSUE TITLE
Production staff persona interviews

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#294]
## Description
Interview production staff to create personas to be used during the course of the Libero Editor project.

## DoD
- [x] Transcribed interviews into a spreadsheet.

## Tasks
- [x] Set up x4 interview sessions with production team
- [x] Add notes taken from interviews to Staff Persona spreadsheet
