### ISSUE TITLE
Create a plan to replace Texture

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#345]
Development of the editor using Texture is proving a lot more difficult than it should, and as such after discussions with some of the stakeholders we decided that it would be worth while investigating what the effort would be to replace it with something else.

Working document...

# Tasks
- [x] Investigate existing libraries and tools that we might be able to use.
- [ ] ~~Make an initial architectural choice on where the 'model' should reside.~~
- [x] Investigate what the other development teams have switched to using and why.
- [x] Capture what texture already does that we don't already have covered in user stories.

# DoD
- [x] A proposal document that details how we intend to replace Texture, and justifies why we feel we need to replace it.
- [x] An estimate, based on the contents of the proposal, that indicates when we think the new completion date for an MVP will be.
