### ISSUE TITLE
Update product backlog

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#346]
With the recent decision to migrate away from Texture and Substance as the base for Libero Editor in favour of ProseMirror, the backlog needs updating to reflect the change.

# DoD
- [x] Updated, estimated, product backlog in Zen Hub containing all the currently known work required for delivery of the Libero Editor MVP

# Tasks
- [x] Remove any issues that are specific to Texture/Substance from the backlog.
- [x] Review and update remaining issues to ensure that the information is correct. E.g DoD criteria.
- [x] Add any new issues for new work that has arisen as a result of the pivot to ProseMirror.
- [x] Conduct a design review of the current designs and the newer designs for tracked changes and querying.
- [x] Review and update estimates for issues.
- [x] Conduct work-breakdowns for the high priority Epics.
- [x] Update the release information in ZenHub to reflect the reset point for the project.
- [x] Present the updated plan and release reports to internal stakeholders.
- [x] Present the updated plan and release reports to external stakeholders.
- [x] Review and update documentation in the Libero shared drive.
- [x] Review and update the product website.
