### ISSUE TITLE
Display and Edit Article Title

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#347]
This issue details the work required to handle display and editing of the 'title-group' element and its child elements.

# User Story

https://github.com/libero/editor/issues/18

# Design

https://projects.invisionapp.com/d/main#/console/19776007/414289303/preview

# DoD
- [x] Title of an article, displayed in the editor as per the design.
- [x] Can edit the title of the article.
- [x] Support for the following markup within the title element. Superscript, Subscript, Italics.
- [x] If no title set, display some placeholder text along the lines of 'Enter title here'.
- [x] Editor, deployed into a staging environment accessible publicly.
- [x] Reviewed and approved by all relevant stakeholders.

**Comment by NuclearRedeye** [comment]
@NickDuf Looking back at the user stories for the article title, there are examples of XML that include translations of titles. Wondering if you have explored how this might work in the designs at all? Reason i ask is that it could be useful to have a visual of how this might work to help inform an technical decisions that we make.

**Comment by NickDuf** [comment]
@NuclearRedeye that's correct. You will notice that there are sets of stories for each ticket. It's really worth me running through these with you so that you have a better understanding of them. In a nutshell the stories at the top for authors and staff are shared by the sig and eLife. The stories further down are more member specific and not needed for all. 

We have no designs to support languages for titles as its not considered part of the MVP.
