### ISSUE TITLE
Display XML Header and DTD Version

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#361]
This issue covers the implementation of support for the `<article>` element.

# User Stories

https://github.com/libero/editor/issues/15

# Design
https://projects.invisionapp.com/d/main#/console/19776007/419110164/preview

# DoD
- [x] Editor updated so that the user can **see** all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.25d
Dev: O.5d

**Comment by NickDuf** [comment]
@ilya-zhuravel all looks good. Minor point to match the 'Libero Editor' size and weight to the design.

**Comment by fred-atherden** [comment]
Thanks - I'm unsure whether we also (or alternatively?) need to display the dtd version from the doctype declaration, e.g.:
```xml
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2d1 20151215//EN" "JATS-archivearticle1.2dtd">
``` 

I think it's probably fine that we don't, but maybe we could discuss in the standup tomorrow.
