### ISSUE TITLE
Display and Edit Author names

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#368]
This issue covers the implementation of support for the `<contrib-group content-type="author">` element.

# User Stories

https://github.com/libero/editor/issues/23
 
### Additional User Stories

- [x] As **production staff**, I want to be able to change the author order so that I can correct mistakes on behalf of the author.
- [x] As **production staff**, I want to be able to add a new author so that I can include any missing authors.
- [x] As **production staff**, I want to be able to remove an author so that I can update the authorship of the article if required.
- [x] As an **author**, I want to be able to edit the first name(s) + initials and surnames for authors so that I can correct any mistakes.
- [x] As an **author**, I want to be able to add a ~~prefix/~~suffix to an author so that I can ensure they are distinguishable from a parent or child with the same name (e.g. Fred Smith Jnr).
- [x] As an **author**, I want to be able to remove a ~~prefix/~~suffix from an author so that I can correct any mistakes.

## Supporting design
- [Author information design](https://invis.io/A8WXRN9PQBF#/414680494_author-Info-1) (5 pages)

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 5d
Development: 3.5d

**Comment by NuclearRedeye** [comment]
Updated user stories to remove mention of 'prefix', as these aren't needed by eLife for MVP.
