### ISSUE TITLE
Display and Edit Author IDs

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#369]
This issue covers the implementation of support for the `<contrib-id>` element.

# User Stories

https://github.com/libero/editor/issues/24

### Additional User Stories

- [x] As **production staff**, I want to be able to remove an ORCID ID from an author so that I can remove errors in ORCID attribution.
- [x] As **production staff**, I need to be able to see whether an ORCID is authenticated so I can ensure the correct information is passed on to the downstream processes.
- [x] As **production staff**, I want to be able to see where an ORCID associated with an author goes so that I can check that correct page is linked. (Is this part of validation?)

### Supporting design
[See orcid input](https://invis.io/A8WXRN9PQBF#/414680495_author-Info-2)

### Design notes
- Users can interact in the same way as they would with a regular text input
- If authenticated="true" in the XML the small green ORCID symbol appear (see design). If authenticated="false" no symbol should be present.

### DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
Estimate:
Design: 0.5d
Dev: 1d
