### ISSUE TITLE
Display and Edit Corresponding author status

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#370]
This issue covers the implementation of support for the `<contrib contrib-type="author" corresp="yes">` element.

# User Stories

https://github.com/libero/editor/issues/25

# Design

https://projects.invisionapp.com/d/main?origin=v7#/console/19776007/414680495/preview?scrollOffset=83
https://projects.invisionapp.com/share/A8WXRN9PQBF#/screens/414680496_author-Info-3

### Additional User Stories

- [x] As **production staff**, I want to be able to remove corresponding author status from an author so that I can correct this information if requested.
- [x] As **production staff**, I want to be able to add corresponding author status to an author so that I can correct this information if requested.

# DoD
- [x] Read the attribute `corresp` from the `contrib` element.
- [x] Edit Author modal updated to include a checkbox to mark an author as corresponding or not.
- [x] Update the author detail section in the main article to display the text and email address as per the design.
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] When an author is marked as the corresponding author, the email address should be displayed in the detailed author information area in the main article view as 'Corresponding author: user@gmail.com'. If an email is present but no corresponding author status is set just the email will be displayed with the prefix. 
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.5d
Dev: 0.5d

**Comment by fred-atherden** [comment]
Looks good for production
