### ISSUE TITLE
Display and Edit Email address

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#371]
This issue covers the implementation of support for the `<email>` element.

# User Stories

https://github.com/libero/editor/issues/34

### Additional User Stories

- [x] As **production staff**, I want to be able to edit an email address associated with an author so that I can correct this information if requested.
- [x] As **production staff**, I want to be able to remove an email address to an author so that I can delete incorrect information.
- [x] As **production staff**, I want to be able to add an email address to an author so that I can add missing information.

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.25d
Dev: 0.5d
