### ISSUE TITLE
Display and Edit Author affiliations

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#372]
This issue covers the implementation of support for the `<aff>` element.

# User Stories

https://github.com/libero/editor/issues/28

### Additional User Stories
- [x]  As an **author**, I want to be able to add or remove affiliations from an author so that I can correct any errors in affiliation attribution.
- [x] As an **author**, I want to be able to add or remove authors from an affiliation so that I can correct any errors in affiliation attribution.
- [x] As an **author**, I want to be able to edit an affiliation so that I can correct any errors.
- [x] As an **author**, I want to be able to create a new affiliation and associate it with existing authors so that I can correct affiliation information.
- [x] As an **author** I want to be able to delete affiliations so that I can remove any added in error.
- [x] As **production staff**, I want to be able to clearly see the divisions between different parts of an affiliation so that I can check it has been structured correctly.

# Design
- [Affiliation](https://invis.io/A8WXRN9PQBF#/417158215_Affiliation-List) (8 pages)

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
Estimate:
Design: 3d
Development: 5d

**Comment by NuclearRedeye** [comment]
Added an additional 4 days for the completion of the persona report.
