### ISSUE TITLE
Display and Edit Author competing interests

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#373]
This issue covers the implementation of support for the `<fn fn-type="COI-statement">` element.

# User Stories

https://github.com/libero/editor/issues/31

### Additional User Stories

- [x] As an **author**, I want to add a competing interest statement to an author so that I can acknowledge conflicts of interest.
- [x] As an **author**, I want to indicate that an author has no competing interests so that this information can be captured.
- [x] As an **author**, I want to be able to edit any competing interests statements so that I can correct any mistakes or update the details.

### Supporting designs
- [Competing interest select menu (click the design to see behaviour)](https://invis.io/A8WXRN9PQBF#/414680497_author-Info-4)
- [author info display (see john hawkes)](https://invis.io/A8WXRN9PQBF#/414680496_author-Info-3)

### Design notes
- Select menu has 3 states. Choose competing interest, No competing interests, Has competing interests
- If 'has competing interests' is chosen an additional 'competing interests statement multi-line text field is added to the card
- if 'no competing interests' is selected the value is set and no additional inputs are added to the card 

### DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate

Design: 0.5d
Development: 3d

**Comment by fred-atherden** [comment]
This looks good for production
