### ISSUE TITLE
Display and Edit Bio

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#374]
This issue covers the implementation of support for the `<bio>` element.

### User Stories

https://github.com/libero/editor/issues/84

### Additional User Stories

- [x] As an **author**, I want to be able to edit a bio so that I can correct any errors.
- [x] As an **author**, I want to be able to add a hyperlink to a bio so that I can link to an external site.
- [x] As an **author**, I want to be able to remove a hyperlink from a bio so that I can correct errors.
- [x] As an **author**, I want to be able to apply formatting to text in a bio so that I can add emphasis.
- [x] As an **author**, I want to be able to remove formatting to text in a bio so that I can correct errors.

### Design(s)
- [Author bio presented on author card with micro tools](https://invis.io/A8WXRN9PQBF#/422420124_author-Info-5)
- [Author bio presented in author information article section](https://invis.io/A8WXRN9PQBF#/414680496_author-Info-3)

### DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.25d
Dev: 1d
