### ISSUE TITLE
Display and Edit Related articles

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#376]
This issue covers the implementation of support for the `<related-article>` element.

# User Stories

https://github.com/libero/editor/issues/20

### Additional User Stories
- [ ] As **production staff**, I want to be able to link two articles so that I can indicate they should be read together.
- [ ] As **production staff**, I want to be able to remove a related article link so that I can respond to changes in publication plans or correct errors.
- [ ] As **production staff**, I want to be able to change the type of link so that I can correct any errors.

# Design
- [Connect article prototype](https://invis.io/3AVVJOBPKZT#/404185921_related-Article)

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.5d
Dev: 2d
