### ISSUE TITLE
Display and Edit Keywords

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#377]
This issue covers the implementation of support for the `<kwd-group>` element.

# User Stories

https://github.com/libero/editor/issues/37

### Additional User Stories
- [x] As an **author**, I want to be able to edit the keywords so that I can correct mistakes.
- [x] As an **author**, I want to be able to add new keywords so that I can include missing information.
- [x] As an **author**, I want to be able to delete keywords associated with my manuscript so that I can make sure that my work is correctly.

# Design
- [Keywords](https://invis.io/A8WXRN9PQBF#/414661275_keywords-Le-Large-Device-S1) (3 pages)

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.5d
Dev: 5d
