### ISSUE TITLE
Display and Edit Abstract

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#378]
This issue covers the implementation of support for the `<abstract>` element.

# User Stories

https://github.com/libero/editor/issues/38

### Additional User Stories
- [x] As an **author**, I want to be able to edit an abstract so that I can correct any errors.
- [ ] ~~As an **author** I want to be able to add sub headings to an abstract so that I can structure the content.~~
- [ ] ~~As an **author**, I want to be able to add and remove equations to an abstract so that I can correct any errors.~~

# Design
- [Abstract designs](https://invis.io/A8WXRN9PQBF#/415857362_Abstract) (5 pages)

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.25d
Dev: 3d

**Comment by NuclearRedeye** [comment]
After discussion, determined that the user stories...
```
As an author I want to be able to add sub headings to an abstract so that I can structure the content.
As an author, I want to be able to add and remove equations to an abstract so that I can correct any errors.
```

Are not actually required for MVP.

At the same time, the styling user story has been moved under the Styling Text Elements Epic
