### ISSUE TITLE
Display and Edit Acknowledgements

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#379]
This issue covers the implementation of support for the `<ack>` elements.

# User Stories

https://github.com/libero/editor/issues/65

### Additional User Stories
- [ ] As an **author**, I want to be able to add an acknowledgements section so that I can include acknowledgements to my manuscript.
- [ ] As an **author**, I want to be able to edit an acknowledgements section for my manuscript so that I can correct errors and add any missing information.
- [ ] As an **author**, I want to be able to add hyperlinks to an acknowledgements section so that I can link out to external resources.
- [ ] As an **author**, I want to be able to add reference or asset citations to my acknowledgements so that I can cite other articles and assets in this context.
- [ ] As an **author**, I want to be able to remove an acknowledgements section so that I can delete redundant information.

# Design
- [Supporting design file](https://invis.io/A8WXRN9PQBF#/425077160_acknowledgements)

# DoD
- [x] Can read and parse the first `ack` element, ignoring the `title` element and display the contents of any `p` elements.
- [x] Support for the same set of marks that we support for the author bio. 
- [ ] Editor updated so that the user can see and edit all the required fields.
- [ ] Solution **reviewed** and **approved** by the designer.
- [ ] Solution **reviewed** and **approved** by required stakeholders.
- [ ] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.25d
Dev: 2d

**Comment by ilya-zhuravel** [comment]
@NickDuf @FAtherden-eLife this is ready for review

**Comment by fred-atherden** [comment]
The link formatting pop-up isn't working, but I imagine that's because it's part of another piece of work?

**Comment by fred-atherden** [comment]
Ilya has cleared up the above, it will be done as part of a separate epic. :+1: from me.

**Comment by NickDuf** [comment]
@ilya-zhuravel works fine for me. Feel free to close the issue.
