### ISSUE TITLE
Display and Edit References

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#380]
This issue covers the implementation of support for the `<ref-list>` element.

# User Stories

https://github.com/libero/editor/issues/77

### Additional User Stories
- [x] As an **author**, I want to be able to add new reference to the article so that I can add missing bibliographic information.
- [x] As an **author**, I want to be able to delete a reference, so that I can remove any erroneous or unnecessary references from the list.
- [x] As an **author**, I want to be able to change a reference type so that I can adjust any incorrectly captured references.
- [x] As an **author**, I want to be able to edit a reference so that I can ensure that the information captured is correct and up to date.
~As an **author**, I want to be able to auto-complete a reference from a database (e.g. crossref, via API), so that I can make sure that the information is entered accurately.~

# Design
- [References](https://invis.io/A8WXRN9PQBF#/418244820_references-1) (4 pages)
- [Reference Types](https://docs.google.com/spreadsheets/d/1pwFkpN-StJq4jZi62G1BAsnppafVEJkoyu_FPPiRFSU/edit#gid=0)

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 5d
Dev: 5d

**Comment by fred-atherden** [comment]
@NickDuf, could you review and tick the 2nd box/close this epic when you have a chance? Thanks! 

I presume that this work:
>As an author, I want to be able to auto-complete a reference from a database (e.g. crossref, via API), so that I can make sure that the information is entered accurately.

will be dealt with during another epic (maybe validation or similar)?
