### ISSUE TITLE
Display and Edit Submission History

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#381]
This issue covers the implementation of support for the `<history>` element.

# User Stories

https://github.com/libero/editor/issues/48

# Design
https://projects.invisionapp.com/d/main#/console/19776007/419110165/preview

# DoD
- [ ] Editor updated so that the user can see and edit all the required fields.
- [ ] Only need to show the 'Published Date' field.
- [ ] Clicking the control should open a date picker, which I can then use to select a date and populate the field.
- [ ] Solution **reviewed** and **approved** by the designer.
- [ ] Solution **reviewed** and **approved** by required stakeholders.
- [ ] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0d
Dev: 0.5d
