### ISSUE TITLE
Display and Edit Sections

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#383]
This issue covers the implementation of support for the `<sec>` element.

# User Stories

https://github.com/libero/editor/issues/40

# Design
- [Design headings hierarchy](https://projects.invisionapp.com/share/A8WXRN9PQBF#/screens/420013660)

### Additional User Stories
- [x] As an **author**, I want to be able to see the hierarchy of section headings within an article so that I can check this is correct.
- [x] As an **author**, I want to be able to add a new heading to my article text so that I can create a new section.
- [x] As an **author**, I want to be able to edit existing headings so that I can correct errors.
- [x] As an **author**, I want to be able to adjust a heading's level of hierarchy within my manuscript so that I can organize my content. (we need extra heading levels to meet SIG requirements)
- [x] As an **author**, I want to be able to delete a heading so that I can merge one section of text into another.

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 1d
Dev: 5d

**Comment by NuclearRedeye** [comment]
Design work broken out.
