### ISSUE TITLE
Display and Edit Paragraphs

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#384]
This issue covers the implementation of support for the `<p>` element.

# User Stories

https://github.com/libero/editor/issues/42

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.25d
Dev: 1d

**Comment by fred-atherden** [comment]
I would expect the acknowledgements to appear after the main body (just before the reference list). Can we move it down in the page?

**Comment by fred-atherden** [comment]
I can't seem to paste with formatting. If you copy text which is, for example, bold and paste it, the pasted text is rendered in roman.

It would be good to have the option to paste with or without formatting (ctrl/cmd + v, and ctrl/cmd + shift + v respectively).

**Comment by fred-atherden** [comment]
Unsure whether we need the spellcheck. I assume it's not a scientific one since gene names are flagged as incorrect. Maybe one to discuss next week or something.

**Comment by fred-atherden** [comment]
Can't format monospace, small caps, or overline in paragraphs. I'm unsure whether this is something we agreed not to do for MVP. eLife don't really need overline, however, while unlikely, it's possible we could use the other two.

**Comment by fred-atherden** [comment]
Other than that looks good. Obviously boxed-text and figure content is displaying, but I imagine the rendering of those will be dealt with in other, later work.

**Comment by NickDuf** [comment]
@ilya-zhuravel @FAtherden-eLife this works fine for me. Copy and paste might be work for another ticket, up to Ilya and the time it takes I would suggest. Monospace, small caps etc should be work as part of the formatting ticket if it is in the menu and an mvp requirement.

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife I'll move acknowledgements down.
Additional formatting will be added later in a different ticker.
Pasting with formatting won't work out of the box. It would require an additional investigation, but I think I saw a solution for this when researching Prosemirror.
Boxes and other things will be dealt with later
