### ISSUE TITLE
Display and Edit Style Elements

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#385]
This issue covers the implementation of support for the `<bold> <italic> <underline> <sup> <sub> <sc> <monospace> <strike> <named-content>` elements.

# User Stories

https://github.com/libero/editor/issues/41

### Additional User Stories
- [x] As an **author**, I want to be able to apply style formatting to my text so that I can add emphasis.
- [x] As an **author**, I want to be able to remove style formatting to my text so that I can correct errors.

- [x] As an **author**, I want to be able to add and remove styling to the text in an **keyword** so that I can correct any errors.
- [x] As an **author**, I want to be able to add and remove styling to the text in an **abstract** so that I can correct any errors.

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
@FAtherden-eLife @JGilbert-eLife Do we need support for the `<named-content>` element? (for gene sequences) for MVP?

CC @NickDuf

**Comment by eLifeProduction** [comment]
No for MVP, @NuclearRedeye - this isn't a requirement in Insights.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.5d
Dev: 2d
