### ISSUE TITLE
Display and Edit Reference citations

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#386]
This issue covers the implementation of support for the `<xref ref-type="bibr">` element.

# User Stories

https://github.com/libero/editor/issues/46

### Additional User Stories
- [x] As an **author**, I want to be able to cite a reference in the text of my article so that I can indicate the relevance of a reference from my references list.
- [x] As an **author**, I want to be able to delete a reference citation so that I can correct mistakes.

# Design
- [Reference citation prototype](https://invis.io/A8WXRN9PQBF#/420138301_citation)

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 2d  
Dev: 3d
