### ISSUE TITLE
Display and Edit Special characters

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#388]
This issue covers the implementation of support for insertion of UTF-8 encoded characters into text.

# User Stories

https://github.com/libero/editor/issues/80

# DoD
- [ ] Editor updated so that the user can see and edit all the required fields.
- [ ] Solution **reviewed** and **approved** by the designer.
- [ ] Solution **reviewed** and **approved** by required stakeholders.
- [ ] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
@FAtherden-eLife Could you compose a paragraph that contains some typical special characters and test that they display correctly in the editor?

**Comment by fred-atherden** [comment]
Here's a paragraph full of Greek and Cyrillic letters pulled from eLife content
αβμγκΔτθηϵζρξδΩσπΦФλϕεΑΣφωψΓΒΨνχΛυΠПοΘϴΧϱ;ΗΙΜΕ΄тΚΝϑМСΟкιΤӧГϫΡИРВЕТНАєΞϿӴЄІςί·ϒήέфϊΏϖѱмШуКхїХΥΖὦ. 

Looks like it renders fine in Editor when I paste it in:
![Screenshot 2020-10-01 at 15.00.32.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/0ce371e4-ef89-4379-abbd-40891e9cf5ff)

Not sure if that's sufficient, or whether you want to add it to an XML file to ensure that it's parsed correctly.
