### ISSUE TITLE
Display and Edit Hyperlinks

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#389]
This issue covers the implementation of support for the `<ext-link>` element.

### User Stories
- https://github.com/libero/editor/issues/82

### Additional User Stories
- [x] As an **author**, I want to be able to make text into a hyperlink so that I can link out to an external URL.
- [x] As an **author**, I want to be able to follow a hyperlink out to the target so that I can check the link is going to the right place.
- [x] As an **author**, I want to be able to remove a hyperlink from the text in the article so that I can make any necessary adjustments before publishing.
- [x] As an **author**, I want to be able to edit the target for a hyperlink so that I can correct any errors.

### Supporting design
- [Hyperlink design including micro controls](https://invis.io/A8WXRN9PQBF#/422420124_author-Info-5)

### Notes
- Hyperlink control can be activated from global toolbar or contextual micro tools
- Follow link can be activated from linked text using command click (as in Microsoft Word)

### DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.5d
Dev: 2d
