### ISSUE TITLE
Display and Edit Lists

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#390]
This issue covers the implementation of support for the `<list>` element.

# User Stories

https://github.com/libero/editor/issues/81

# Examples

[See example document](https://docs.google.com/document/d/1FJAPEOOXsG5FLVf_eX7Sx4rI-m4tlBw29bhOncW67Jc/edit)

### Numbered (ordered) list
![Screenshot 2020-09-24 at 13.56.56.png](https://images.zenhubusercontent.com/5d556d4eb2cb743d37f7bb25/d3fc8b4f-d949-4c03-b047-415bbf5ef45d)

### Bulleted (unordered) list
![Screenshot 2020-09-24 at 13.57.02.png](https://images.zenhubusercontent.com/5d556d4eb2cb743d37f7bb25/0cc31ea2-ef6a-4ab3-ac74-3ef158e1a027)

# Tasks
- [x] Investigate and try existing ProseMirror plugins for list support and lets see how they work/behave.

# DoD
- [x] Support for creating a Bulleted (unordered) list, Numerical (ordered) list, see above images.
- [x] Can use the list options from the Text menu to create a new list and list item at the cursors current location.
- [x] Can highlight a block of text, and then select one of the list options from the Text menu and have each paragraph in the selection converted to a list item in a new list.
- [ ] ~~Can use `tab` and `shitft+tab` to increase or decrease the depth of a list item.~~
- [x] Pressing `return` whilst inside a `list-item` should create an empty `list-item` and move the cursor to right place.
- [x] Pressing backspace at the start of a `list-item` should first remove the paragraph from the list, and then if pressed again should remove the indentation. **(Needs further discussion!)**
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.5d
Dev: 3d
