### ISSUE TITLE
Display and Edit Boxes

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#391]
This issue covers the implementation of support for the `<boxed-text>` element.

# User Stories

https://github.com/libero/editor/issues/54

### Additional User Stories
- [x] As an **author**, I want to be able see box content for my article so that I can check this is correct
- [x] As an author, I want to be able see box content for my article so that I can check this is correct
- [x] As an author, I want to be able to add a box to my article so that I can include information to support the main text.

# Design
- [ ] [Design](https://projects.invisionapp.com/d/main#/console/19776007/429902078/preview) Note, first 2 pages ONLY

# DoD
- [x] Can, from the insert menu the user can select 'box' which will insert a box at the current cursor position in the main article.
- [x] Can edit the contents of the box. Needs to support multiple paragraphs and bold, italic, sup, sub, xlink. Same as the reference field basically.
- [x] Can display the contents of boxes that are already in the XML, as per the design.
- [x] Can delete a box using the trash can affordance. 
- [x] Can undo/redo creation of the box.
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 1d
Dev: 2d
