### ISSUE TITLE
Display and Edit Figures

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#393]
This issue covers the implementation of support for the `<fig>` element.

## User Stories
https://github.com/libero/editor/issues/49

## Design
- [Figure management design](https://invis.io/A8WXRN9PQBF#/430713002_figure-1)

## DoD
- [x] User can insert a figure from the insert menu at the current cursor position in the main article body.
- [x] User can select from the default file picker which file they want to upload. Options should be limited to JPG and PNG.
- [x] Figures should display in the main article body as per the design.
- [x] Support for editing the following fields, label, title, legend and attribution. 
- [x] Title, Legend and Attribution fields should support the following marks, bold, italic, sub, sup, xlink and citations.
- [x] User can delete a figure using the appropriate affordance.
- [x] User can undo/redo insertion/deletion of a figure.
- [x] User can change the figure using the appropriate affordance to select another file to replace it.
- [x] User can move a figure using the appropriate affordance to drag it around the main article body.
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 3d
Dev: 6d
