### ISSUE TITLE
Display and Edit Table

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#394]
This issue covers the implementation of support for the `<table-wrap>` element.

# User Stories

https://github.com/libero/editor/issues/57

# DoD
- [ ] Editor updated so that the user can see and edit all the required fields.
- [ ] Solution **reviewed** and **approved** by the designer.
- [ ] Solution **reviewed** and **approved** by required stakeholders.
- [ ] New version of the Editor, deployed to the staging environment and publicly accessible.
