### ISSUE TITLE
Display and Edit Asset-level licensing

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#397]
This issue covers the implementation of support for the `<permissions>` element as a child of the `<table-wrap>` element.

# User Stories

https://github.com/libero/editor/issues/79

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 2d
Dev: 4d
