### ISSUE TITLE
Capture User Stories

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#4]
_As a **DEVELOPER**, I want to capture the user stories for the project so that I know what features are required for the new system._

It is essential that we capture the user stories for all the new features and functionality that is desired for the new system.

**DoD:**
- [x] User Stories captured, reviewed and documented in the Producer Workspace

**Tasks:**
- [x] Finish cleaning up the existing user stories.
- [x] Migrate user stories from current location to Libero Producer Project Workspace.
