### ISSUE TITLE
Update the Keywords component to meet accessibility requirements

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#420]
# What do we need to know more about
- Navigation using keyboard.

# Tasks
- [x] Gather requirements from the SIG.
- [x] Understand more about screen readers.
- [x] Update an existing component, e.g. Keywords, to work with a screen reader.
- [x] Understand/Investigate how the ProseMirror editor component works with screen readers.

# DoD
- [ ] The keyword component, updated to support a screen reader and any other accessibility features that we need to support.
