### ISSUE TITLE
Accessibility support for Libero Editor

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#427]
# Tasks
- [x] Test Libero Editor using an agreed tool set for accessibility issues
- [x] Develop a single report of uncovered usability issues
- [ ] Establish a plan for addressing uncovered issues

# DoD
- [ ] An agreed list of usability issues and action plan for Libero Editor to meet necessary accessibility standards

# Related materials
- [Accessibility statements](https://github.com/israelcefrin/Accessibility-Statement)
- [Libero Editor accessibility report (Israel Cefrin)](https://drive.google.com/file/d/1hXdDWQTpDs7I4U2Lxn-CmYk0BuewYvTE/view?usp=sharing)

**Comment by NickDuf** [comment]
@discodavey do the above tasks and dod seem accurate to you?

**Comment by discodavey** [comment]
@NickDuf Sorry for not seeing this. Yes. I think they are accurate enough for the time being.

I have done the initial testing for the majority of the main issues. There maybe more after we have done the initital list.

The list is in the ticket
https://github.com/libero/editor/issues/469

Tickets will be made from this list.

**Comment by NickDuf** [comment]
@discodavey we also need to run a comparison with Israel's list, which should give us a good starting point.

**Comment by discodavey** [comment]
@NickDuf Have we got that list and can we link it on either here or the ticket above?
