### ISSUE TITLE
Display and Edit Article Info

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#468]
This issue covers the implementation of support for the `<journal-meta>` element.

### User Stories
- https://github.com/libero/editor/issues/16
- https://github.com/libero/editor/issues/17
- https://github.com/libero/producer/issues/21
- https://github.com/libero/producer/issues/22
- https://github.com/libero/producer/issues/35
- https://github.com/libero/producer/issues/36
- https://github.com/libero/producer/issues/47

### Additional User Stories
- [x] As **production staff**, I want to be able to see the and edit the article info so that I can check this information is correct.

### Designs
https://projects.invisionapp.com/share/A8WXRN9PQBF#/screens/419110164

### DoD
- [x] Editor updated so that the user can **see**  all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by Maelplaine** [comment]
@NickDuf Can you tick the 2nd box?
