### ISSUE TITLE
Support for Impact Statements

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#481]
# User Stories
https://app.zenhub.com/workspaces/libero-editor-5d56a6cfaa13c900012ad75b/issues/libero/editor/38

# Design
[Impact statement design](https://invis.io/A8WXRN9PQBF#/425061398_Impact_Statement)

# Tasks
- [x] Update the store to extract multiple abstracts and also extract the the type.
- [x] Update the abstract component to toggle display label based on type.
- [x] Update the article view to display an impact statement after the abstract.

# DoD
- [x] Can display and edit an impact statement type abstract.
- [x] Reviewed and approved by designer
- [x] Reviewed and approved by stakeholders
- [x] Deployed to production environment.

**Comment by NickDuf** [comment]
@ilya-zhuravel looks good just needs placeholder text 'Enter impact statement'

**Comment by fred-atherden** [comment]
Looks good - see above PR to change the tagging in the article so that the Impact statement can be pulled in.
