### ISSUE TITLE
1st round software based accessibility testing

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#489]
## Description
Libero Editor is accessibility tested to AA standards using 3rd party software with uncovered issues to be addressed by eLife/SIG engineers. 

## Tasks
- [ ] eLife/SIG stakeholders to conduct first round of software based accessibility tests
- [ ] eLife/SIG engineers to address reported issues
- [ ] Libero Editor Software reviewed by relevant stakeholders 

## Dod
- [ ] Raised issues by accessibility testing software are acceptably addressed
- [ ] Adjusted software is approved by Libero Editor and SIG stakeholders
- [ ] Libero Editor is scheduled for further software tests
