### ISSUE TITLE
2nd round software based accessibility testing

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#491]
## Description
Libero Editor is retested to AA standards using 3rd party software to check uncovered issues have been successfully addressed. Any outstanding issues to be addressed by eLife/SIG engineers. 

## Tasks
- [ ] eLife/SIG stakeholders to conduct 2nd round of software based accessibility tests
- [ ] eLife/SIG engineers to address any remaining issues
- [ ] Libero Editor Software reviewed by relevant stakeholders 

## Dod
- [ ] Libero passes software based accessibility tests
- [ ] Software testing adjustments are approved by Libero Editor and SIG stakeholders
- [ ] Libero Editor is scheduled for RNIB formal accessibility tests
