### ISSUE TITLE
1st round RNIB user based accessibility testing

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#492]
## Description
Libero Editor is to be formally tested by RNIB live users to uncover any issues missed by accessibility software tests with issues accordingly addressed by eLife/SIG engineers. 

## Tasks
- [ ] RNIB to conduct first round of testing and provide eLife and report issues
- [ ] eLife/SIG engineers to address reported issues
- [ ] RNIB requested to review software fixes 

## Dod
- [ ] Raised issues by RNIB are acceptably addressed
- [ ] Adjusted software is approved by Libero Editor and SIG stakeholders
- [ ] RNIB requested to test again
