### ISSUE TITLE
Final round RNIB user based accessibility testing

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#493]
## Description
We aim to address any remaining usability items to meet the AA accessibility standard based on the final round of accessibility testing conducted by RNIB testers.  

## Tasks
- [ ] RNIB to conduct final round of testing and provide eLife and report issues
- [ ] eLife/SIG engineers to address reported issues
- [ ] Libero Editor Software reviewed by relevant stakeholders 

## Dod
- [ ] Raised issues by RNIB are acceptably addressed
- [ ] Adjusted software is approved by Libero Editor and SIG stakeholders
- [ ] Libero Editor meets the AA accessibility standards
