### ISSUE TITLE
Define the MVP

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#5]
_As a **PRODUCT OWNER**, I need to define the minimal viable product so that the team knows what to build._

We need to define the MVP for Producer so that we can start identifying the features that are required and hence put together a plan of work to achieve that.

**DoD:**
- [ ] A product backlog, that captures all the features and known work required to deliver the MVP.

**Tasks:**
- [x] Discussion with Exeter to discuss technical options for integration.
- [x] Review current eLife production workflow and identify parts suitable for replacement by MVP.
- [x] Review Texture UI/UX to determine what it has and what work might be needed.
- [x] Technical analysis of Texture to gauge suitability.
- [x] Add details of technical choices to the Technical Specification document.
- [x] Update Technical Specification document to reflect MVP goals.
- [x] Update Design Specification document to reflect MVP goals.
- [x] Review Technical Specification with eLife technical team.
