### ISSUE TITLE
Labels not related to input fields

### ISSUE THREAD

**Issue by discodavey** [libero/editor#501]
## Description
Input labels need to be related to their input fields so the screen readers can associate and read them correctly.

## Tasks
- [ ] Add for="" attribute to labels
- [ ] Add unique id="" and corresponding name="" value to input fields
- [ ] Use name, for and id to associate labels with input fields

## DoD
- [ ] Screen readers relate labels with the input fields

**Comment by NickDuf** [comment]
@discodavey would you mind taking a look at the tasks to make sure they accurate.

**Comment by discodavey** [comment]
This one looks good.
