### ISSUE TITLE
Edit buttons missing aria label and description

### ISSUE THREAD

**Issue by discodavey** [libero/editor#504]
## Description
Edit button missing aria label to describe the edit button and what it enables editing for.

## Tasks
- [ ] Add aria labels to edit buttons
- [ ] Edit button action is added to aria label. e.g. 'edit affiliation'

## DoD
- [ ] Edit button action and relationship is read out by screen readers.

**Comment by NickDuf** [comment]
@discodavey would you expect this from the tasks?

**Comment by discodavey** [comment]
@NickDuf Yes, I would expect this.
