### ISSUE TITLE
Add button text contrast fails on hover/focus state

### ISSUE THREAD

**Issue by discodavey** [libero/editor#505]
## Description
old 
When the focus is on the small labels ie. Affiliations, Abstract etc the foreground/background contrast fails. foreground: #767676 background: #cfcfcf. @NickDuf to supply new colour.

new
Add buttons below content areas fail accessibility text contrast standards when in hover and focus state.

## Tasks
old
- [ ] Background colour on the label when focused to be changed so it passes W3C contrast

new
- [ ] Designer to supply guidance on button styling to pass contrast accessibility issue 
- [ ] Add button to be updated based on guidance 

## DoD
- [ ] Add button text on focus/hover states pass W3C contrast checker
