### ISSUE TITLE
Keyword actions are not available for keywords

### ISSUE THREAD

**Issue by discodavey** [libero/editor#506]
## Description
Article keywords actions are not understood for screen readers or available through keyboard controls. 

## Tasks
- [ ] Tab key first focuses keywords label
- [ ] Tab key moves through the list per item starting with text then delete affordance
- [ ] Delete affordance action must readable by screen readers. e.g. 'delete aging'
- [ ] Edit action while on author should be engaged through key CMD/ctrl. 'CMD e'
- [ ] Edit action should be read out by screen reader when on keywords label. 'Article keywords section. Press CMD/ctrl e while on a keyword to edit. Hit return to save.  

## DoD
- [ ] Keywords are screen readable including section label and available actions.

**Comment by NickDuf** [comment]
@discodavey one of the more tricky patterns for accessibility. Would this list of tasks meet the standard?

**Comment by discodavey** [comment]
We need to check if using CMD E would trigger other functions on a Mac or Windows or even Linux.
