### ISSUE TITLE
Modal window field names are not read out

### ISSUE THREAD

**Issue by discodavey** [libero/editor#507]
## Description
Input labels are skipped on tab and not read out by screen readers.

## Tasks
- [ ] Add for="" attribute to labels
- [ ] Add unique id="" and corresponding name="" value to input fields
- [ ] Use name, for and id to associate labels with input fields
- [ ] Inputs and labels are keyboard navigable

## DoD
- [ ] Screen readers relate labels with the input fields

**Comment by NickDuf** [comment]
@discodavey is this the same problem as before? Input label for tag and input id and name are missing?

**Comment by discodavey** [comment]
They seem to just skip them altogether so probably best to make sure labels are in. If not then add aria-label.
