### ISSUE TITLE
Keyboard dismiss for modal windows

### ISSUE THREAD

**Issue by discodavey** [libero/editor#508]
## Description
Users with accessibility needs must navigate through an entire cards information before they can dismiss the modal state.

## Tasks
- [ ] Setup keyboard ESC key to close modal windows.
- [ ] Set aria tag on modals to inform the user they are opening a modal. 

## DoD
- [ ] It is possible to dismiss modal window using the ESC key.

**Comment by NickDuf** [comment]
@discodavey how would the user know that they could use the escape key? would the screen reader tell them when the modal opens or something?

**Comment by discodavey** [comment]
It's a standard thing known to users with screen readers. When the modal window opens there would be a aria role with alert or diaglog which would or should tell them they are in a modal window. I know that alert does this.

It might be worth researching which one is the better of the two.

**Comment by NickDuf** [comment]
@discodavey thanks. I have added a second task to reflect your comment. Does this seem clear?

**Comment by discodavey** [comment]
All looks good.
