### ISSUE TITLE
Navigation to be in list form

### ISSUE THREAD

**Issue by discodavey** [libero/editor#509]
## Description
The article outline in the sidebar is not keyboard navigable or screen reader friendly.

## Tasks
- [ ] Structure the article outline to enable keyboard navigation.
- [ ] Tag outline items to enable screen reading.

## DoD
- [ ] Article outline is keyboard navigable and screen reader friendly.

**Comment by NickDuf** [comment]
@ would it suffice to make the buttons keyboard navigable?

**Comment by discodavey** [comment]
If these are in an unordered list they will be keyboard navigable. They should then tab correctly as well as having a nav tag around it.
