### ISSUE TITLE
Remove duplicate ID attributes

### ISSUE THREAD

**Issue by discodavey** [libero/editor#510]
## Description
Remove 'id' attribute duplicates from the application. 

## Tasks
- [ ] Check and update id attributes in the application to be unique.

## DoD
- [ ] No duplicate id attributes on elements in the applications code.
- [ ] Id attributes represent the element they are associated with.

**Comment by NickDuf** [comment]
@discodavey can you remind us what accessibility issue this causes?

**Comment by discodavey** [comment]
This is more to do with best practice on coding. You should never has two ID's the same in the page but duplicate IDs can cause problems in screen readers. If two or more elements on the same page share the same ID, this can cause problems in screen readers which use IDs for labeling controls and table headings.
