### ISSUE TITLE
Reference snagging list

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#519]
## Description
Minor snagging fixes to reference management feature.

## Tasks
- [x] Editor inputs should have 1 row by default to be consistent with authors design pattern [See example for default editors input](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/4625ce5a-f5b1-40d7-af04-28e0a506bf3c)
- [x] Add new reference should be set to journal reference type by default
- [x] Bug on input auto complete for book reference. 1. Add your self as an editor and hit auto complete to add your name type details. Information is added to the author input above
- [x] Update to reference unmapped elements state to match [design and comment guidance in inVision](https://invis.io/A8WXRN9PQBF#/428274829_references-Swap)

## Dod
- [ ] Task list items are complete and signed-off by Team

**Comment by NickDuf** [comment]
@FAtherden-eLife would you mind offering input on task item 2? the choice is article by default or please choose.

**Comment by fred-atherden** [comment]
Thanks @NickDuf, Journal by default would be preferable.

**Comment by fred-atherden** [comment]
I'm no longer seeing the auto-complete pop-up.
