### ISSUE TITLE
Edit reference citation

### ISSUE THREAD

**Issue by Maelplaine** [libero/editor#524]
## User stories
- [x] As an author, I want to be able to identify reference citations in the text so that I can check they are correct.
~ - [ ] As an Author, I want to be able to cite a reference in the text of my article so that I can indicate the relevance of a reference from my references list. ~
- [x] As an author, I want to be able to delete a reference citation so that I can correct mistakes.

## Design reference
- [Reference citation (3 pages)](https://invis.io/A8WXRN9PQBF#/420138301_citation)

# Tasks
- [x] Render modal for reference citation
- [x] Display a blue tick next to selected reference as [per design](https://projects.invisionapp.com/share/A8WXRN9PQBF#/screens/420143605)
- [ ] ~ Clicking on an unselected reference should add that reference to the citation separated by a semi-colon and a space ~
- [x] Clicking on a selected reference should remove it, and placeholder text '???' should be displayed.
- [x] Filter box should filter by sub-string in any of the field of reference information
- [x] Add an affordance to clear filter box 

## Dod
- [x] Authors and staff should be able to change a reference citation in the article's main body

**Comment by fred-atherden** [comment]
References need to be rendered in the following way:
- 1 author -> Surname, year
- 2 authors -> Surname1 and Surname2, year
- 3+ authors -> Surname1 et al., year

Currently, when edited, what they all do is:
surname given-names et al.. year
![Screenshot 2020-08-28 at 11.31.41.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/23f7883d-30ff-41a7-970f-643ee39568ca)

**Comment by fred-atherden** [comment]
Filtering ins't working quite as I expected. I think it's because it's capitalisation specific.

For example in [54296](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296), searching 'trans' brings this up:
![Screenshot 2020-08-28 at 12.07.41.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/14783934-2232-4358-b372-ad66b9ddf77f)

Whereas searching 'Trans' brings this up:
![Screenshot 2020-08-28 at 12.07.53.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/4e3d6ec2-ddfc-4105-9e8b-3e493b00e18d)

Would be nice if it could ignore capitalisation.

**Comment by fred-atherden** [comment]
I can't see any X affordance to clear the search in the 'Filter list' field. Although I guess this is not _necessary_ for MVP.

**Comment by NickDuf** [comment]
@ilya-zhuravel @FAtherden-eLife  all fine from me. I agree with Fred's comments above. The clear cross would be nice it it can be done quickly but not essential.

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife your feedback has been addressed

**Comment by fred-atherden** [comment]
Thanks @ilya-zhuravel.

It looks like the given-names are still being placed in the citation text. For example here:
![Screenshot 2020-09-03 at 09.47.28.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/b9d480f2-ccb1-44b5-b82d-25bf4694aba9)
It should be `Greer et al., 2010`, not `Greer EL et al., 2010`. 

Also, in the case, where there is one or two authors, a full stop appears after the name(s), when instead it should be a comma. 

For example, and editing the first reference so that it has only one author, the citation displays as:
![Screenshot 2020-09-03 at 09.49.08.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/9c635b1d-99ed-4eaa-b19c-772e7c530f97)

When it should say Greer, 2010.

**Comment by fred-atherden** [comment]
The other two issues look good to me.

**Comment by NuclearRedeye** [comment]
- Adjust colour of clear filter affordance to match the 'action grey' used on the toolbar buttons.
- Allow user to click to deselect reference and set placeholder text on citation to '???'.

**Comment by fred-atherden** [comment]
Looks good to me. I've raised [a new ticket](https://app.zenhub.com/workspaces/libero-editor-5d56a6cfaa13c900012ad75b/issues/libero/editor/537) for a separate issue/requirement I noticed.
