### ISSUE TITLE
Add reference from the edit citation modal

### ISSUE THREAD

**Issue by Maelplaine** [libero/editor#525]
## User stories
- [x] As an Author, I want to be able to cite a reference in the text of my article so that I can indicate the relevance of a reference from my references list.

## Tasks
- [x] An affordance to add reference should be displayed
- [x] When click should show add reference modal with journal type selected
- [x] When done is clicked add reference to citation and to the main application state (reference list)

## Dod
- [x] Authors and staff should be able to cite a reference from the articles reference list in the article's main body text.

**Comment by fred-atherden** [comment]
Looks good to me - thanks @ilya-zhuravel.
