### ISSUE TITLE
Snagging list

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#527]
## Tasks
- [x] Change article type to 'Insight' (see screen shot 1 and xml sample)
- [x] View inputs to be same min-height as card inputs (see screen shots 2, 3, 4)
- [x] Related articles: All cards apart from alerts are to be same width (see screen shot 5)

## Reference
- [XML sample for item 1](https://github.com/libero/editor-reference-manuscripts/blob/faa1db3aae98636b9a59a262c88e345f26d4954a/manuscripts/54296/elife-54296.xml#L23-L25)
- [Screenshot 1](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/2bd711a6-ecd7-4773-84c1-8f22d596d8a6)
- [Screenshot 2](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/cec88a70-29a5-4d31-a4ab-1bfec239400c)
- [Screenshot 3](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/fe4a2345-5042-4462-9f36-1e3cfb22364a)
- [Screenshot 4](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/bc7d4c21-d5b3-4454-8e39-040284d046b4)
- [Screenshot 5](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/44b8f95d-af41-43fa-81d3-565a69825d2f)

## Dod
- [ ] Snagging list is resolved and approved by designer

**Comment by NickDuf** [comment]
@ilya-zhuravel let me know if you need anything else.

**Comment by NickDuf** [comment]
@ilya-zhuravel all items complete except No2. Feel free to reach out if you need more clarity from me.

**Comment by NickDuf** [comment]
@ilya-zhuravel all good just affiliations input remaining.
