### ISSUE TITLE
Update the backend to support serving image files

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#544]
From the bundles, need to grab the additional image assets, convert them from tiff to either png or jpg, store them and update the article-store to allow the client to get the images for a specified article.

# DoD
- [x] Can make an API call to the backend that can retrieve the specified image for an article.

# Subtasks
- [x] Modify SQS listener to convert tiff to jpg (upload both tiff and jpg objects)
- [ ] During sqs queue - build out a manifest of all assets using articleId as reference
- [x] Serve assets based on path

**Comment by Cooryd** [comment]
No longer need to create an asset manifest to achieve DoD, assets now available at `articles/:articleid/assets/:fileKey`
