### ISSUE TITLE
Update the + affordances on the article view to address user feedback

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#557]
# Description

The affordances on the article view for adding a new item/entity didn't fair to well in user testing and hence need adjusting.

![Screenshot 2020-10-08 at 13.40.31.png](https://images.zenhubusercontent.com/5d556d4eb2cb743d37f7bb25/ed381b6b-4b1a-45ac-af4a-e2ff3ccfa76c)

# Tasks
- [x] Update design.
- [ ] Update Editor as per design.

# DoD
- [ ] Affordances updated as per the updated design.
- [ ] Changes committed and deployed to staging environment.
- [ ] Solution reviewed and approved by stakeholders.

**Comment by NickDuf** [comment]
@ilya-zhuravel the add button you have created for adding figure licences is a suitable replacement for updating the add pattern everywhere else it is used.

I will also update my design.

**Comment by fred-atherden** [comment]
Do we also need it updated here (in the reference citation dropdown)? @NickDuf? 
![Screenshot 2020-11-16 at 15.15.34.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/819c84ff-2df9-4aa4-808d-eb5f390bb6c9)

Otherwise looks good to me.

**Comment by NickDuf** [comment]
@FAtherden-eLife we do. All instances need to be updated across the interface. In this instance It's a simple text and colour change.

**Comment by fred-atherden** [comment]
Looks like it's been updated. @NickDuf all OK?

**Comment by NickDuf** [comment]
@ilya-zhuravel all looks fine to me. Just Fred's comment above to be addressed.

**Comment by ilya-zhuravel** [comment]
@NickDuf it's all been addressed now. Closing the ticket
