### ISSUE TITLE
Change the Subject drop down controls to work like the reference author list

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#560]
# Description

The drop down controls in the article info section to change the subjects didn't test very well, and as such needs to be changed. Based on feedback, it should be changed to work like the 'author list' component in the 'edit reference' modal.

# Tasks
- [ ] Updated design.
- [ ] Editor updated as per the design.

# DoD
- [ ] Component updated as per the design.
- [ ] User can add a subject
- [ ] User can remove a subject.
- [ ] User can select a subject using the drop down control.
- [ ] User can remove all subjects.
- [ ] User can add as many subjects as they like.
- [ ] Solution reviewed and approved by stakeholders.
- [ ] Updated Editor deployed onto the staging environment.
