### ISSUE TITLE
Detect xml file added to 'kryia' bucket and store within DB

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#563]
# Tasks

- [ ] use SQS interface to detect file being added. Read file contents from S3 bucket
- [ ] set up local postgres container and schema for storing xml data
- [ ] store extracted xml content in DB entry

# Questions / Details

- What is the directory structure of the kryia bucket? 
- What are the zip file naming conventions?
