### ISSUE TITLE
Create an initial design for Queries

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#570]
# User stories
See issue #73

# Tasks
- [ ] Gather the initial requirements.
- [ ] Produce an early design proposal.

# DoD
- [ ] An inVision design file, shared with the relevant stakeholders to gather feedback.
