### ISSUE TITLE
Adjust indentation of sections in the table of contents

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#599]
# Description

The indentation of the section heading in the table of contents need adjusting. At present, we simple have either indented or not, what we want is that each heading level is indented, e.g.
```
Heading 1
  Heading 2
    Heading 3
      Heading 4
    Heading 3
  Heading 2
```

# Supporting design
- inVision file with comments [here](https://invis.io/A8WXRN9PQBF#/437977149_title-Appbar-Le-Large-Device-Toc-Opt2)

# Tasks
- [ ] What do we do with long headings? Truncate? Ellipsis?

# DoD
- [ ] Editor updated so that the table of contents panel shows sections as above.
- [ ] Solution reviewed and approved by stakeholders.
- [ ] Deployed to production.

**Comment by NuclearRedeye** [comment]
0.5 day design, 0.5 day implementation...

**Comment by NickDuf** [comment]
@ilya-zhuravel I have added the inVision file above. Let me know if you need any further guidance or have any questions.

**Comment by NickDuf** [comment]
@ilya-zhuravel looks good to me. The text wrapping might be a little off. Look at the 'of in the heading 4 example below.

![Screenshot 2020-11-23 at 15.36.18.png](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/c9f0d2ce-e2eb-46de-9ebd-9200e0b82217)

**Comment by NickDuf** [comment]
@ilya-zhuravel works fine for me now. Problem solved.

**Comment by fred-atherden** [comment]
Looks good to me
