### ISSUE TITLE
Update builder so that it creates the security group for docdb

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#635]
# Description

For `editor-article-store` to access the database, the inbound port 27017 for docdb access needs to be open. I've validated that manually creating a new security group `elife-libero-editor-staging` and opening the above port for inbound traffic resolves the connection issue, but this now needs to be added to `builder` so that the group is created automatically.

# Tasks
- [x] Raise a draft PR with the proposed changes.
- [ ] Once merged, validate that the new security group works.
- [ ] Remove the manually created `elife-libero-editor-staging` security group via the aws management console.

# DoD
- [ ] Builder updated to create the correct config for both staging and production.
- [ ] Solution reviewed and merged
- [ ] Editor staging and production instances verified as connecting to documentdb cluster.
