### ISSUE TITLE
Convert v2 XML from Editor to v1 on export

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#661]
The following transform should be applied to XML which is being delivered from Editor to either Kriya (for PDF generation) or Continuum (for publication).
[https://app.zenhub.com/files/195217312/a1e34e9a-061b-494c-a3cc-544742d4d1c6/download](https://app.zenhub.com/files/195217312/a1e34e9a-061b-494c-a3cc-544742d4d1c6/download)

Both files are zipped because ZenHub/GitHub does not support the filetype.

# Tasks

- [ ] Investigate what libraries are available to handle the transform for us.
- [ ] Update the code to do the transforms.

# DoD

- [ ] XML that is imported from the production processes bucket should be processed through the importing XSLT.
- [ ] XML that is exported from the Editor backend should be processed through the export XSLT.

**Comment by Cooryd** [comment]
Limit this issue to applying the XSLT to imported articles. We can raise another issue around transforming back when we take on the PDF generation work.
