### ISSUE TITLE
Run an instance of Libero Editor Locally.

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#700]
# Description

At the moment, there isn't any really clear instructions for a user on how they can run Libero Editor either locally on their own machine or on another system that they have access to. This means that when somebody [stumbles across the pinned repo for Editor](https://github.com/libero/editor), there isn't any instructions that they can follow to easily run and play with the Editor.

# Tasks
- [ ] Add a docker-compose file that can be used to bring up a local instance of Libero Editor with some test content.
- [ ] Update the README.md file to include some quick start instructions.

# DoD
- [ ] User can clone the [libero/editor](https://github.com/libero/editor), follow the quick start instructions and locally run an instance of Libero Editor.

**Comment by NuclearRedeye** [comment]
I've already done some ground work [here](https://github.com/NuclearRedeye/editor-reverse-proxy/tree/wip/dev-stack), and have a compose file that just needs tweaking but should do the job. I'll migrate this over to the Editor repo and clean it up so that it can be used to run the latest release published on dockerhub, hence the 1 day estimate.
