### ISSUE TITLE
Create a new Editor Deployment that is suitable for public demo

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#701]
# Description

Since we've updated Editor to support ingesting real content, and migrated the over from the `flux-test` to the `flux-prod` cluster there isn't an instance of Editor that is suitable for demonstration publicly.

# Tasks
- [ ] Deploy a new instance of Libero Editor that can be accessed publicly.
- [ ] Update that instance so that anybody can ingest content and then test to see how that is displayed in the Editor
- [ ] Create some instructions that explain to users how they can interact with the demo.
- [ ] Update the Libero Editor project website to either include instructions and a link to the demo, or embed the demo in an iFrame.
- [ ] Create a cron job, or similar, that flushes or restarts the demo at some frequency to stop data accumulating.
- [ ] Advertise the instance to the SIG.

# DoD
- [ ] An instance of Libero Editor, publicly accessible, where a user can upload some JATS XML content and try to view it in the Demo instance.

**Comment by Cooryd** [comment]
No longer required.
