### ISSUE TITLE
Update the documentation in libero/editor to document our development process

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#702]
# Description

To try and encourage users outside the organisation to engage more with the Editor project, it would be a good idea to update our documentation to cover how our process works and point people towards the ZenHub board alongside an explanation on how the board works and how we go about using it. This could go in the README.md file, although it might make more sense in another file.

# Tasks
- [x] Update the documentation to detail our development process.
- [ ] ~Add a link to the ZenHub board.~
- [ ] ~~Add some information that details how the ZenHub board works.~~

# DoD
- [ ] Documentation, added to the [Editor repository](https://github.com/libero/editor) that details our day to day development process.

**Comment by Cooryd** [comment]
Lets remember to include Ilya's handover documents in the readme docs.
