### ISSUE TITLE
Create some teams in the Libero organisation for 3rd party contributors

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#703]
# Description

We should create some new teams in the Libero organisation for various SIG members that can be used to include specific groups of people in conversations, development or decision making. Looking at the current setup, we have created teams following the current hierarchy...

```
organstation
 - department
    - user
```

Hence, we should create this setup for the existing members of the SIG, and then create some umbrella teams that include all the developers or all the designers at the various orgs. This would then make it much easier to @ mention groups in issues, and help us to be more inclusive with our development.

# Tasks
- [ ] Create new teams for the various organistations that we work with, and add the relevant users to each group.
- [ ] Create some umbrella teams for the Editor SIG, and add the relevant teams.

# DoD
- [ ] User can @ mention on any issue in the Libero organisation members of the Editor SIG by various groups.
