### ISSUE TITLE
Should we be making use of libero.pub to communicate progess on Libero Editor?

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#704]
# Description

During a recent brainstorming session about things we could do to improve our communication and engagement relating to the Editor project, the question came up around if we should be doing more with the current project pages on [libero.pub](https://libero.pub) or if we should be trying to create a new project homepage elsewhere. With MVP approaching, it would be good to have somewhere that serves as a landing page of sorts to help others discover the project, so we need to make a choice about where this information should be.

# Tasks
- [ ] Define some goals that define what a project site for Libero Editor should be.
- [ ] Make a call about if we can build on the existing libero project site or not.
- [ ] Either way, create new issues in the backlog that details the next steps for updating and maintaining the site.

# DoD
- [ ] A decision about the goals of the site and where it should be located.
- [ ] Next steps, raised as new issues in the backlog.

**Comment by Cooryd** [comment]
Yes, we will now be repurposing libero.pub as a demo sciencebeam -> editor demo
