### ISSUE TITLE
Add ISO_3166-1 2 letter country code support to editor

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#719]
Design proposal is [here](https://invis.io/A8WXRN9PQBF#/418480046_author-Affiliation-3)

##### User stories
   - [ ]  As an author, I want to be able to set a country for my affiliation so that I can provide accurate information about my place of work
   - [ ]  As a Production Editor I need to be sure that an authors affiliation information is complete, so that I can meet specified journal standards

##### Constraints
- [ ] We need a politically neutral set of options for users to choose a country from
- [ ] Making an incorrect choice should not be possible. i.e. by selecting a country the correct ISO will be assigned if there is one
- [ ] Staff can trust the system resulting in one less check. Libero Editor is designed to promote less need for manual checks making proofing more accurate and efficient

**Comment by Cooryd** [comment]
https://material-ui.com/components/autocomplete/#autocomplete was decided as being a good fit for the select
