### ISSUE TITLE
Update editor helm charts to define CPU and Memory request values.

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#733]
# Description

We had an incident over the weekend where Editor was scheduled onto a rather busy node, and hence we had a lot of alerts firing about CPU load which ultimately resulted in the performance of some services degrading. We think this could be mitigated by updating the charts to [set the CPU and Memory request values](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container) which should help the scheduler to make a better decision about which node to deploy to pods to.

# Tasks

- [ ] Work out a sensible value for CPU request for the Editor containers.
- [ ] Update the charts to define these values.

# Definition of Done

- [ ] Charts updated for `editor-article-store` and `editor-client` to set CPU request and Memory request values.
- [ ] Solution deployed into a staging environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders.
- [ ] Solution deployed into a production environment and accessible to users.

**Comment by Cooryd** [comment]
Grafana link to check resource usage https://grafana.elifesciences.org/
