### ISSUE TITLE
Add generate endpoint to editor-pdf-service

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#822]
# Description
We should add a `/generate/${id}` endpoint to the `editor-pdf-service`. For now this should simply take a request with a path param of the article ID then internally call off to the `editor-article-stores` with a head request to ensure the article exists. On successful responses of this call it should simply return a 200 response. It should also handle failure of the request and return the appropriate response / log as expected.

## Tasks

- [x] add a POST endpoint for `/generate/${id}` to the express service
- [x] add a config option for `editor-article-stores` urls
- [x] add HEAD request to article-store `/articles/${id}` to ensure article exists.
- [x] handles 404 response correctly
- [x] handles 500 response correctly
