### ISSUE TITLE
Support use of libero/editor-client in PKP / Stencila applications

### ISSUE THREAD

**Issue by NateWr** [libero/editor#830]
## Description

As a developer of OJS, our journal publishing software, I want to integrate libero/editor-client so that journals that run our software can use libero/editor-client to edit their JATS XML files. I'd like to discuss changes to the way that the client app is configured, packaged and distributed in order to simplify the long-term maintenance of the integration.

You can see an [annotated commit](https://github.com/NateWr/editor-client/commit/f11c673515897ff2a773f61d59d04f227435f7de) that introduces a few of the configuration changes that we needed to make. This is a rough hack, and not a proposal for the actual implementation. But it should give you an idea of the kinds of configuration options we need.

## Proposals/Requests

- [ ] Distribute libero/editor-client as a node package to encapsulate dependencies. See description below.
- [ ] Allow the app to be configured when it is initialized through documented configuration options. See description below.
- [ ] Allow all strings to be localized (eg - via the configuration options).
- [ ] Not a requirement, but ideally the application would used named CSS classes instead of automatically generated ones so that CSS customizations could be applied without recompiling the JavaScript.

## Distribute as node package

libero/editor-client is structured as a SPA. That means the repository combines the editor itself with a static page where it is built/deployed. To integrate this, I had to add the repository as a submodule, build the project assets in the repository, and then construct a page within our application that loaded those files. Since the filenames change with each build, there's no reliable way to link to the assets.

The only other option, as far as I can see, would be to fully reproduce the dependency list and build steps in our application. We have our own build process for our application's assets, so we'd need to integrate these build processes into one, and maintain that integration over time. This will be prone to problems.

It would be great if the application was distributed as a node package, separately from the SPA (ie - the assets in the public directory). That would permit us to integrate the editor with our own build process, and its dependencies would be internalized within libero/editor-client.

In ideal world, our integration would be as simple as adding the editor to our dependencies and then importing and rendering it.

```json
{
    "dependencies": {
        "libero/editor-client": "^1.0"
    }
}
```

```js
import { App } from 'libero/editor-client';

App.render(document.getElementById('root'));
```

This would avoid a whole trainload of maintenance headaches for us down the road.

## Configuration options

As a rough hack, I'm simply declaring a global configuration object and reading that in when the app is initialized (see [example](https://github.com/NateWr/editor-client/commit/f11c673515897ff2a773f61d59d04f227435f7de#diff-290dfbfe5d92ad411e56b24a73a25bed89a9cc2a66af5f24c2367bcf87814bf8R51)). However, I'm sure that there are better ways to handle this. One way or another, we're going to need a set of reliable, documented configuration options.

Ideally we'd be able to pass these in when the app is rendered:

```js
import { App } from 'libero/editor-client';

App.render(
    document.getElementById('root')
    {
        manuscriptUrl: '...',
        figureUploadUrl: '...',
        changesUrl: '...',
        etc: {}
    }
);
```

But I'm new to the React/Redux ecosystem. There may be a standard way to do this. Here's my working list of things that would need to be configurable:

- All URLs for the manuscript, figures, and changes.
- Any URLs for assets like the Noto Sans font (it loads from the static directory which assumes the editor is running at domain.com/)
- The ability to configure which editor parts are available (and to have these reflected in the TOC)
- The ability to extend the menu bar (at the bare minimum, to add a link, but ideally to be able to add a button that could interact with state or fire a callback or something)
- Not immediately required, but eventually: the ability to pass in a citation style (CSL) to use
