### ISSUE TITLE
Publish an npm package for editor-client react component library

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#839]
# Description

PKP would like to embed `editor-client` into their OJS application as a react component rather than deploy the entire application. The usage should be as follows...

package.json
```json
{
    "dependencies": {
        "libero/editor-client": "^1.0"
    }
}
```

index.ts
```js
import { App } from 'libero/editor-client';

App.render(document.getElementById('root'));
```

# Tasks
- [ ] Update the build targets to add a new target to build the client as a redistributable component ideal for packaging as a library.
- [ ] Should consider adding a code example that shows usage, perhaps as a new repository.

# Definition of Done
- [ ] Can run a new target, e.g. `npm run build-lib` that packages/bundles the client as a component in a library.
- [ ] The library can be imported into another application, and the editor embedded into that app.
- [ ] Package published automatically to npm on each change by the CI, with the version number suffixed with `alpha`.
- [ ] Package published automatically to npm when tagged by the CI.
