### ISSUE TITLE
Define new MVP goal and prioritize

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#906]
# Description

We need to outline exactly what we expect to achieve given the timeframe of 3-4 months to tie off this project, and what the goal of the project is, e.g.

## Tasks
- [x] How does this align with the organisation goals? Is it even worth finishing?
- [x] Can we actually do enough in the next 3 to 4 months to get it to where we need to?
- [x] Who is the product owner for the new Editor project?
- [x] What is the scope of the new MVP?
- [x] What work do we need to do to achieve the new goal?
- [x] Are there any additional requirements from the SIG members that we should be focusing on?
- [x] Do we still want to put together a demo site with Editor and ScienceBeam?
- [x] Who is going to maintain any demo infrastructure?

## DoD
- [x] Backlog updated with all the desired work to achieve the new MVP goal in priority order.
- [x] Ideally, EPIC's ballpark estimated so that we have some indication of what we can achieve in the time allowed.
- [x] Roadmap updated.
- [x] Release plan updated.
