### ISSUE TITLE
UX Snagging

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#913]
### Page title
- [ ] Page title incorrect size - will link a design ref

### Boxes and figures
- [ ] Can't place cursor before first box without deleting box
- [ ] Figure drag appears to be broken
- [ ] Boxes and figure styles are inconsistent. 1 drop shadow, other outline. We should pick one

### Cards
- [ ] Windows machines, unwanted scrollbars on cards
- [ ] Cancel, Done buttons on cards can be hidden from view. We may want to fix the controls section
- [ ] Shadow to be added to micro-controls. Icons look disabled
- [ ] Bug with hyperlinking bio text
- [ ] Modal over modal to be slightly wider for clarity, shadow would help

### Menu
- [ ] Do all formatting options work? Mono, Small caps, Overline
- [ ] Bullets select all items to set bullet style broken
- [ ] Tab doesn't work - usability issue 
- [ ] Does preformat option work in paragraph menu
- [x] Does save option work? it's always disabled
- [ ] Buttons in toolbar look disabled. Should be same colour as text
- [ ] Unclear save status. could we indicate when it does?

### Spacing
- [ ] Margin before typography and media need to be organised
- [ ] References vertical space is too great

### Keywords
- [ ] Bug editing keywords (see video)
- [ ] Spacing to be consistent
- [ ] Input area should have an outline
