### ISSUE TITLE
Setup a GitHub Project Board for Libero Editor

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#942]
# Description

As a final step in winding down the project, we should close down the ZenHub board and migrate everything over to a GitHub project board which will be more accessible for anybody finding the project.

# Tasks
- [ ] Create a new GitHub project board
- [ ] Create the relevant pipelines in the new board
- [ ] Add issues to the board
- [ ] Delete ZenHub Board
- [ ] Disconnect ZenHub from the Libero Organisation

# DoD
- [ ] ZenHub project board deleted
